import type { InteractiveExample, OrbitalQuizQuestion } from "./types"

export const INTERACTIVE_EXAMPLES: InteractiveExample[] = [
  {
    id: "ch4",
    name: "CH4",
    category: "organic",
    electronConfiguration: "C: 1s2 2s2 2p2; H: 1s1",
    hybridization: "Carbon is sp3.",
    orbitalDiagram: "Four C sp3 orbitals overlap with four H 1s orbitals.",
    moDiagram: "Localized sigma framework; full diatomic MO diagram not used.",
    sigmaPiDecomposition: "4 sigma bonds, 0 pi bonds.",
    bondOrder: "Each C-H bond is approximately bond order 1.",
    homo: "C-H sigma bonding set",
    lumo: "C-H sigma antibonding set",
    magnetism: "Diamagnetic",
    lonePairs: "No central-atom lone pairs.",
    explanation: "Methane is a clean tetrahedral sp3 example.",
  },
  {
    id: "nh3",
    name: "NH3",
    category: "inorganic",
    electronConfiguration: "N: 1s2 2s2 2p3; H: 1s1",
    hybridization: "Nitrogen is sp3.",
    orbitalDiagram: "Three sp3 orbitals bond to H; one sp3 orbital holds a lone pair.",
    moDiagram: "Localized sigma framework.",
    sigmaPiDecomposition: "3 sigma bonds, 0 pi bonds.",
    bondOrder: "Each N-H bond is approximately bond order 1.",
    homo: "Nitrogen lone-pair orbital",
    lumo: "N-H sigma antibonding set",
    magnetism: "Diamagnetic",
    lonePairs: "One sp3 lone pair on nitrogen.",
    explanation: "Electron geometry is tetrahedral, while molecular geometry is trigonal pyramidal.",
  },
  {
    id: "h2o",
    name: "H2O",
    category: "inorganic",
    electronConfiguration: "O: 1s2 2s2 2p4; H: 1s1",
    hybridization: "Oxygen is sp3.",
    orbitalDiagram: "Two sp3 orbitals bond to H; two sp3 orbitals hold lone pairs.",
    moDiagram: "Localized sigma framework.",
    sigmaPiDecomposition: "2 sigma bonds, 0 pi bonds.",
    bondOrder: "Each O-H bond is approximately bond order 1.",
    homo: "Oxygen lone-pair orbitals",
    lumo: "O-H sigma antibonding set",
    magnetism: "Diamagnetic",
    lonePairs: "Two sp3 lone pairs on oxygen.",
    explanation: "Two lone pairs compress the H-O-H angle below the tetrahedral ideal.",
  },
  {
    id: "co2",
    name: "CO2",
    category: "inorganic",
    electronConfiguration: "C: 1s2 2s2 2p2; O: 1s2 2s2 2p4",
    hybridization: "Carbon is sp; oxygens are approximately sp2.",
    orbitalDiagram: "Carbon sp orbitals form sigma bonds; two p orbitals form pi bonds.",
    moDiagram: "Intro localized double-bond model.",
    sigmaPiDecomposition: "2 sigma bonds, 2 pi bonds.",
    bondOrder: "Each C=O bond is approximately bond order 2.",
    homo: "Oxygen lone-pair / pi nonbonding set",
    lumo: "C=O pi antibonding orbital",
    magnetism: "Diamagnetic",
    lonePairs: "Two lone pairs on each oxygen.",
    explanation: "CO2 is linear because carbon has two electron domains.",
  },
  {
    id: "o2",
    name: "O2",
    category: "diatomic",
    electronConfiguration: "Each O: 1s2 2s2 2p4",
    hybridization: "Not described by central-atom hybridization.",
    orbitalDiagram: "MO filling places two electrons in degenerate π*2p orbitals.",
    moDiagram: "σ1s σ*1s σ2s σ*2s σ2p π2p π*2p",
    sigmaPiDecomposition: "One sigma component and one net pi component.",
    bondOrder: "2",
    homo: "π*2p",
    lumo: "σ*2p",
    magnetism: "Paramagnetic",
    lonePairs: "Lone-pair language is less useful than the MO model.",
    explanation: "O2 is paramagnetic because it has two unpaired antibonding pi electrons.",
  },
  {
    id: "n2",
    name: "N2",
    category: "diatomic",
    electronConfiguration: "Each N: 1s2 2s2 2p3",
    hybridization: "Not described by central-atom hybridization.",
    orbitalDiagram: "MO filling reaches a filled σ2p level.",
    moDiagram: "σ1s σ*1s σ2s σ*2s π2p σ2p",
    sigmaPiDecomposition: "One sigma component and two pi components.",
    bondOrder: "3",
    homo: "σ2p",
    lumo: "π*2p",
    magnetism: "Diamagnetic",
    lonePairs: "Each nitrogen has a lone-pair-like sigma electron pair in localized descriptions.",
    explanation: "N2 has a strong triple bond and no unpaired electrons.",
  },
  {
    id: "benzene",
    name: "Benzene",
    category: "organic",
    electronConfiguration: "Six sp2 carbons, each contributing one p electron.",
    hybridization: "Each carbon is sp2.",
    orbitalDiagram: "Six p orbitals overlap cyclically above and below the ring.",
    moDiagram: "Six pi MOs: three bonding filled, three antibonding empty.",
    sigmaPiDecomposition: "12 sigma bonds and a delocalized six-electron pi system.",
    bondOrder: "C-C bonds average between single and double.",
    homo: "Degenerate filled aromatic pi orbitals",
    lumo: "Degenerate aromatic pi antibonding orbitals",
    magnetism: "Diamagnetic",
    lonePairs: "No heteroatom lone pairs in benzene.",
    explanation: "Benzene is aromatic because six pi electrons occupy bonding cyclic pi orbitals.",
  },
  {
    id: "ethanol",
    name: "Ethanol",
    category: "organic",
    electronConfiguration: "C and O valence shells arranged in localized sigma bonds.",
    hybridization: "Both carbons and oxygen are sp3.",
    orbitalDiagram: "C-C, C-H, C-O, and O-H sigma bonds; oxygen has two lone pairs.",
    moDiagram: "Localized sigma framework.",
    sigmaPiDecomposition: "8 sigma bonds, 0 pi bonds.",
    bondOrder: "All framework bonds are approximately bond order 1.",
    homo: "Oxygen lone-pair orbital",
    lumo: "C-O or O-H sigma antibonding set",
    magnetism: "Diamagnetic",
    lonePairs: "Two sp3 lone pairs on oxygen.",
    explanation: "Ethanol demonstrates lone pairs on an sp3 oxygen inside a saturated molecule.",
  },
  {
    id: "ethene",
    name: "Ethene",
    category: "organic",
    electronConfiguration: "Each carbon is sp2 with one unhybridized p electron.",
    hybridization: "Both carbons are sp2.",
    orbitalDiagram: "sp2 sigma framework plus p-p side overlap.",
    moDiagram: "Filled C=C pi orbital, empty C=C pi* orbital.",
    sigmaPiDecomposition: "5 sigma bonds, 1 pi bond.",
    bondOrder: "C=C is bond order 2.",
    homo: "π C=C",
    lumo: "π* C=C",
    magnetism: "Diamagnetic",
    lonePairs: "No lone pairs.",
    explanation: "Ethene is the classic pi-bond builder example.",
  },
  {
    id: "ethyne",
    name: "Ethyne",
    category: "organic",
    electronConfiguration: "Each carbon is sp with two unhybridized p orbitals.",
    hybridization: "Both carbons are sp.",
    orbitalDiagram: "sp sigma framework plus two perpendicular pi bonds.",
    moDiagram: "Two filled C≡C pi bonding orbitals.",
    sigmaPiDecomposition: "3 sigma bonds, 2 pi bonds.",
    bondOrder: "C≡C is bond order 3.",
    homo: "C≡C pi bonding set",
    lumo: "C≡C pi antibonding set",
    magnetism: "Diamagnetic",
    lonePairs: "No lone pairs.",
    explanation: "Ethyne shows why sp carbons are linear.",
  },
  {
    id: "acetone",
    name: "Acetone",
    category: "organic",
    electronConfiguration: "Carbonyl C and O use p orbitals for the pi bond.",
    hybridization: "Carbonyl carbon and oxygen are sp2; methyl carbons are sp3.",
    orbitalDiagram: "C=O sigma plus pi bond; oxygen lone pairs remain.",
    moDiagram: "Filled C=O pi orbital, low-lying pi* acceptor.",
    sigmaPiDecomposition: "9 sigma bonds, 1 pi bond.",
    bondOrder: "C=O is approximately bond order 2.",
    homo: "Oxygen lone-pair / pi bonding orbitals",
    lumo: "C=O pi* orbital",
    magnetism: "Diamagnetic",
    lonePairs: "Two lone pairs on oxygen.",
    explanation: "Acetone is a good carbonyl HOMO/LUMO example.",
  },
  {
    id: "acetic-acid",
    name: "Acetic Acid",
    category: "organic",
    electronConfiguration: "Carboxyl group includes conjugated oxygen and carbon p orbitals.",
    hybridization: "Carboxyl carbon is sp2; hydroxyl oxygen is resonance-influenced.",
    orbitalDiagram: "C=O pi system plus O-H/C-O sigma bonds.",
    moDiagram: "Carboxyl pi and lone-pair interactions.",
    sigmaPiDecomposition: "7 sigma bonds, 1 delocalized pi component.",
    bondOrder: "C-O bonds show resonance-averaged character.",
    homo: "Oxygen lone-pair rich orbital",
    lumo: "Carboxyl pi* orbital",
    magnetism: "Diamagnetic",
    lonePairs: "Two lone pairs on each oxygen.",
    explanation: "Acetic acid connects carbonyl pi bonding with acidic O-H behavior.",
  },
  {
    id: "aniline",
    name: "Aniline",
    category: "organic",
    electronConfiguration: "A benzene pi system plus an amino lone pair.",
    hybridization: "Ring carbons are sp2; nitrogen is partially sp2 by conjugation.",
    orbitalDiagram: "Nitrogen lone pair can overlap with the aromatic pi system.",
    moDiagram: "Aromatic pi system perturbed by amino donation.",
    sigmaPiDecomposition: "Aromatic sigma framework plus delocalized pi bonding.",
    bondOrder: "Ring C-C bonds are resonance-averaged.",
    homo: "Amino lone-pair / aromatic pi donor orbital",
    lumo: "Aromatic pi* orbital",
    magnetism: "Diamagnetic",
    lonePairs: "One nitrogen lone pair, partly conjugated.",
    explanation: "Aniline shows lone-pair donation into an aromatic system.",
  },
  {
    id: "phenol",
    name: "Phenol",
    category: "organic",
    electronConfiguration: "A benzene pi system plus oxygen lone pairs.",
    hybridization: "Ring carbons are sp2; oxygen is resonance-influenced.",
    orbitalDiagram: "One oxygen lone pair can overlap with the aromatic pi system.",
    moDiagram: "Aromatic pi system perturbed by oxygen donation.",
    sigmaPiDecomposition: "Aromatic pi system plus O-H/C-O sigma bonds.",
    bondOrder: "Ring bonds are resonance-averaged.",
    homo: "Oxygen lone-pair / aromatic pi donor orbital",
    lumo: "Aromatic pi* orbital",
    magnetism: "Diamagnetic",
    lonePairs: "Two oxygen lone pairs, one more conjugated than the other.",
    explanation: "Phenol connects lone pairs, acidity, and aromatic pi donation.",
  },
  {
    id: "acetonitrile",
    name: "Acetonitrile",
    category: "organic",
    electronConfiguration: "Nitrile C and N are sp with two pi bonds.",
    hybridization: "Nitrile carbon and nitrogen are sp.",
    orbitalDiagram: "C≡N sigma plus two perpendicular pi bonds.",
    moDiagram: "Filled nitrile pi orbitals and low-lying pi* acceptors.",
    sigmaPiDecomposition: "4 sigma bonds, 2 pi bonds.",
    bondOrder: "C≡N is bond order 3.",
    homo: "Nitrogen lone-pair / nitrile pi set",
    lumo: "C≡N pi* orbital",
    magnetism: "Diamagnetic",
    lonePairs: "One lone pair on nitrogen in an sp orbital.",
    explanation: "Acetonitrile is a linear sp nitrile example.",
  },
]

export const QUIZ_QUESTIONS: OrbitalQuizQuestion[] = [
  {
    id: "o2-homo",
    prompt: "Which orbital is the HOMO in O2 after filling?",
    hiddenLabel: "O2 MO diagram",
    choices: ["σ2p", "π*2p", "σ*2p", "σ1s"],
    correctAnswer: "π*2p",
    explanation: "O2's highest occupied electrons are the two unpaired electrons in degenerate π*2p orbitals.",
    topic: "HOMO/LUMO",
  },
  {
    id: "methane-hybridization",
    prompt: "What hybridization gives methane its tetrahedral electron geometry?",
    hiddenLabel: "Four equivalent hybrid orbitals",
    choices: ["sp", "sp2", "sp3", "sp3d"],
    correctAnswer: "sp3",
    explanation: "Methane has four bonding domains around carbon, so the carbon uses four sp3 orbitals.",
    topic: "Hybridization",
  },
  {
    id: "water-lone-pairs",
    prompt: "Where are the two lone pairs in water placed in this model?",
    hiddenLabel: "Bent molecule with two hidden occupied orbitals",
    choices: ["Two sp3 orbitals", "Two π* orbitals", "Two σ* orbitals", "Two d orbitals"],
    correctAnswer: "Two sp3 orbitals",
    explanation: "Water has four electron domains around oxygen: two bonds and two sp3 lone-pair orbitals.",
    topic: "Lone Pairs",
  },
  {
    id: "ethene-pi",
    prompt: "Which bond in ethene is the π bond?",
    hiddenLabel: "C=C with labels hidden",
    choices: ["C-H overlap", "C-C head-on overlap", "Side-by-side p overlap", "O-H overlap"],
    correctAnswer: "Side-by-side p overlap",
    explanation: "The second component of the C=C double bond comes from sideways p-orbital overlap.",
    topic: "Sigma/Pi",
  },
  {
    id: "n2-bond-order",
    prompt: "What bond order does the introductory MO diagram predict for N2?",
    hiddenLabel: "N2 MO diagram",
    choices: ["1", "2", "3", "0"],
    correctAnswer: "3",
    explanation: "N2 has 10 bonding and 4 antibonding electrons, so bond order is (10 - 4) / 2 = 3.",
    topic: "Bond Order",
  },
]

export function listInteractiveExamples() {
  return INTERACTIVE_EXAMPLES
}

export function getInteractiveExample(id: string) {
  return INTERACTIVE_EXAMPLES.find((example) => example.id === id) ?? INTERACTIVE_EXAMPLES[0]
}
