import type { IonRecord } from "../types"

const boards = ["high-school", "ib-sl", "ib-hl", "ap", "a-level", "university-intro"] as const

function ion(
  partial: Omit<IonRecord, "kind" | "examBoards" | "topics" | "subtopics" | "tags"> &
    Partial<Pick<IonRecord, "topics" | "subtopics" | "tags">>,
): IonRecord {
  return {
    kind: "ion",
    examBoards: [...boards],
    topics: partial.topics ?? ["ions"],
    subtopics: partial.subtopics ?? [],
    tags: partial.tags ?? [partial.type],
    ...partial,
  }
}

export const ALL_IONS: IonRecord[] = [
  ion({
    id: "ion-h-plus",
    name: "hydrogen ion",
    formula: "H+",
    charge: 1,
    type: "monoatomic",
    aliases: ["H+", "proton", "hydronium precursor"],
    isCommonIon: true,
    tags: ["acid"],
  }),
  ion({
    id: "ion-oh-minus",
    name: "hydroxide",
    formula: "OH-",
    charge: -1,
    type: "monoatomic",
    aliases: ["OH-", "hydroxide ion"],
    isCommonIon: true,
    tags: ["base"],
  }),
  ion({
    id: "ion-nh4-plus",
    name: "ammonium",
    formula: "NH4+",
    charge: 1,
    type: "polyatomic",
    aliases: ["NH4+", "ammonium ion"],
    isCommonIon: true,
    subtopics: ["acid-base"],
  }),
  ion({
    id: "ion-no3-minus",
    name: "nitrate",
    formula: "NO3-",
    charge: -1,
    type: "polyatomic",
    aliases: ["NO3-", "nitrate ion"],
    isCommonIon: true,
    subtopics: ["resonance", "lewis-structures"],
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-no2-minus",
    name: "nitrite",
    formula: "NO2-",
    charge: -1,
    type: "polyatomic",
    aliases: ["NO2-", "nitrite ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-co3-2-minus",
    name: "carbonate",
    formula: "CO3^2-",
    charge: -2,
    type: "polyatomic",
    aliases: ["CO3^2-", "CO32-", "carbonate ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-so4-2-minus",
    name: "sulfate",
    formula: "SO4^2-",
    charge: -2,
    type: "polyatomic",
    aliases: ["SO4^2-", "SO42-", "sulfate ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance", "hypervalent"],
  }),
  ion({
    id: "ion-so3-2-minus",
    name: "sulfite",
    formula: "SO3^2-",
    charge: -2,
    type: "polyatomic",
    aliases: ["SO3^2-", "sulfite ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-po4-3-minus",
    name: "phosphate",
    formula: "PO4^3-",
    charge: -3,
    type: "polyatomic",
    aliases: ["PO4^3-", "PO43-", "phosphate ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-clo4-minus",
    name: "perchlorate",
    formula: "ClO4-",
    charge: -1,
    type: "polyatomic",
    aliases: ["ClO4-", "perchlorate ion"],
    isCommonIon: true,
    tags: ["polyatomic", "hypervalent", "resonance"],
  }),
  ion({
    id: "ion-mno4-minus",
    name: "permanganate",
    formula: "MnO4-",
    charge: -1,
    type: "polyatomic",
    aliases: ["MnO4-", "permanganate ion"],
    isCommonIon: true,
    oxidationStates: [7],
    tags: ["polyatomic", "redox"],
  }),
  ion({
    id: "ion-cr2o7-2-minus",
    name: "dichromate",
    formula: "Cr2O7^2-",
    charge: -2,
    type: "polyatomic",
    aliases: ["Cr2O7^2-", "dichromate ion"],
    isCommonIon: true,
    oxidationStates: [6],
    tags: ["polyatomic", "redox"],
  }),
  ion({
    id: "ion-cn-minus",
    name: "cyanide",
    formula: "CN-",
    charge: -1,
    type: "polyatomic",
    aliases: ["CN-", "cyanide ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-scn-minus",
    name: "thiocyanate",
    formula: "SCN-",
    charge: -1,
    type: "polyatomic",
    aliases: ["SCN-", "thiocyanate ion"],
    isCommonIon: true,
    tags: ["polyatomic", "resonance"],
  }),
  ion({
    id: "ion-i3-minus",
    name: "triiodide",
    formula: "I3-",
    charge: -1,
    type: "polyatomic",
    aliases: ["I3-", "triiodide ion"],
    isCommonIon: true,
    tags: ["polyatomic", "expanded-octet"],
  }),
  ion({
    id: "ion-fe-2-plus",
    name: "iron(II)",
    formula: "Fe^2+",
    charge: 2,
    type: "monoatomic",
    aliases: ["Fe2+", "Fe^2+", "ferrous ion"],
    isCommonIon: true,
    oxidationStates: [2],
    tags: ["transition-metal"],
  }),
  ion({
    id: "ion-fe-3-plus",
    name: "iron(III)",
    formula: "Fe^3+",
    charge: 3,
    type: "monoatomic",
    aliases: ["Fe3+", "Fe^3+", "ferric ion"],
    isCommonIon: true,
    oxidationStates: [3],
    tags: ["transition-metal"],
  }),
  ion({
    id: "ion-cu-2-plus",
    name: "copper(II)",
    formula: "Cu^2+",
    charge: 2,
    type: "monoatomic",
    aliases: ["Cu2+", "Cu^2+"],
    isCommonIon: true,
    oxidationStates: [2],
  }),
  ion({
    id: "ion-ag-plus",
    name: "silver(I)",
    formula: "Ag+",
    charge: 1,
    type: "monoatomic",
    aliases: ["Ag+"],
    isCommonIon: true,
    oxidationStates: [1],
  }),
  ion({
    id: "ion-cl-minus",
    name: "chloride",
    formula: "Cl-",
    charge: -1,
    type: "monoatomic",
    aliases: ["Cl-", "chloride ion"],
    isCommonIon: true,
  }),
  ion({
    id: "ion-na-plus",
    name: "sodium ion",
    formula: "Na+",
    charge: 1,
    type: "monoatomic",
    aliases: ["Na+"],
    isCommonIon: true,
  }),
]

export function getIonByFormula(formula: string): IonRecord | undefined {
  const q = formula.replace(/\s/g, "").toLowerCase()
  return ALL_IONS.find(
    (i) =>
      i.formula.replace(/\s/g, "").toLowerCase() === q ||
      i.aliases.some((a) => a.replace(/\s/g, "").toLowerCase() === q),
  )
}
