import { mechanismSimulatorHref } from "../interactive-learning/mechanisms"
import { molecularExplorerHref } from "../interactive-learning/molecular-explorer"
import { createKnowledgeEdge, type ChemistryKnowledgeEdge } from "./knowledge-edge"
import { createKnowledgeNode, type ChemistryKnowledgeAction, type ChemistryKnowledgeNode } from "./knowledge-node"

function action(label: string, href: string): ChemistryKnowledgeAction {
  return { label, href }
}

function practice(topic: string) {
  return `/practice-generator?topic=${encodeURIComponent(topic)}&source=database`
}

function exam(topic: string) {
  return `/exam-generator?topic=${encodeURIComponent(topic)}&source=database`
}

function node(input: Omit<ChemistryKnowledgeNode, "searchText">): ChemistryKnowledgeNode {
  return createKnowledgeNode(input)
}

function edge(from: string, to: string, type: ChemistryKnowledgeEdge["type"], label: string, weight = 1) {
  return createKnowledgeEdge(from, to, type, label, weight)
}

export const KNOWLEDGE_GRAPH_NODES: ChemistryKnowledgeNode[] = [
  node({
    id: "compound:benzene",
    type: "compound",
    label: "Benzene",
    subtitle: "C6H6",
    description: "Aromatic six-membered ring and central example for delocalization, spectroscopy, and EAS mechanisms.",
    curriculum: ["Organic Chemistry I", "Spectroscopy"],
    difficulty: "Intermediate",
    tags: ["arene", "aromatic", "ring", "C6H6"],
    completed: true,
    actions: [
      action("Open Molecular Explorer", molecularExplorerHref({ compound: "benzene" })),
      action("Open Mechanism Simulator", mechanismSimulatorHref({ reaction: "benzene-bromination", compound: "benzene" })),
      action("Practice Benzene", practice("Aromaticity")),
    ],
  }),
  node({
    id: "compound:phenol",
    type: "compound",
    label: "Phenol",
    subtitle: "C6H5OH",
    description: "A benzene derivative where oxygen lone-pair donation changes acidity and ring reactivity.",
    curriculum: ["Organic Chemistry I", "Spectroscopy"],
    difficulty: "Intermediate",
    tags: ["benzene derivative", "alcohol", "aromatic"],
    actions: [action("Open Molecular Explorer", molecularExplorerHref({ compound: "phenol" })), action("Practice Functional Groups", practice("Functional Group Identification"))],
  }),
  node({
    id: "compound:aniline",
    type: "compound",
    label: "Aniline",
    subtitle: "C6H5NH2",
    description: "Aromatic amine with lone-pair donation into the ring.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["amine", "aromatic", "benzene derivative"],
    actions: [action("Open Molecular Explorer", molecularExplorerHref({ compound: "aniline" })), action("Practice Mechanisms", practice("Organic Mechanisms"))],
  }),
  node({
    id: "compound:toluene",
    type: "compound",
    label: "Toluene",
    subtitle: "C6H5CH3",
    description: "Alkylbenzene related to benzene through electrophilic aromatic substitution patterns.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["arene", "benzene derivative", "alkylbenzene"],
    actions: [action("Practice Aromatics", practice("Aromaticity"))],
  }),
  node({
    id: "compound:nitrobenzene",
    type: "compound",
    label: "Nitrobenzene",
    subtitle: "C6H5NO2",
    description: "Electron-poor benzene derivative used for directing-effect comparisons.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Advanced",
    tags: ["arene", "nitro", "deactivating"],
    actions: [action("Practice Aromatics", practice("Aromaticity"))],
  }),
  node({
    id: "compound:acetone",
    type: "compound",
    label: "Acetone",
    subtitle: "CH3COCH3",
    description: "Simple ketone connecting carbonyl hybridization, IR, NMR, and nucleophilic addition.",
    curriculum: ["Organic Chemistry I", "Spectroscopy"],
    difficulty: "Intermediate",
    tags: ["carbonyl", "ketone", "IR 1715"],
    actions: [action("Open Molecular Explorer", molecularExplorerHref({ compound: "acetone" })), action("Open Mechanism Simulator", mechanismSimulatorHref({ reaction: "carbonyl-addition", compound: "acetone" }))],
  }),
  node({
    id: "compound:ethanol",
    type: "compound",
    label: "Ethanol",
    subtitle: "CH3CH2OH",
    description: "Alcohol example tying together hybridization, hydrogen bonding, lab technique, spectroscopy, and oxidation.",
    curriculum: ["Organic Chemistry I", "Laboratory Skills"],
    difficulty: "Beginner",
    tags: ["alcohol", "OH", "solvent"],
    actions: [action("Open Molecular Explorer", molecularExplorerHref({ compound: "ethanol" })), action("Practice Alcohols", practice("Functional Group Identification"))],
  }),
  node({
    id: "functional-group:carbonyl",
    type: "functionalGroup",
    label: "Carbonyl",
    subtitle: "C=O",
    description: "Polar pi bond that explains IR peaks, nucleophilic addition, and sp2 trigonal planar geometry.",
    curriculum: ["Organic Chemistry I", "Spectroscopy"],
    difficulty: "Intermediate",
    tags: ["ketone", "aldehyde", "C=O", "electrophile"],
    actions: [action("Practice Carbonyls", practice("Carbonyl Chemistry")), action("Generate Exam Set", exam("Carbonyl Chemistry"))],
  }),
  node({
    id: "functional-group:alcohol",
    type: "functionalGroup",
    label: "Alcohol",
    subtitle: "R-OH",
    description: "Hydroxyl functional group connecting hydrogen bonding, oxidation, IR O-H stretch, and lab solvents.",
    curriculum: ["Organic Chemistry I", "Spectroscopy", "Laboratory Skills"],
    difficulty: "Beginner",
    tags: ["OH", "hydrogen bonding", "oxidation"],
    actions: [action("Practice Alcohols", practice("Functional Group Identification"))],
  }),
  node({
    id: "functional-group:arene",
    type: "functionalGroup",
    label: "Arene",
    subtitle: "aromatic ring",
    description: "Aromatic hydrocarbon functional group explaining benzene derivatives and EAS chemistry.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["benzene", "aromatic", "ring"],
    actions: [action("Practice Aromaticity", practice("Aromaticity"))],
  }),
  node({
    id: "hybridization:sp2",
    type: "hybridization",
    label: "sp2 Hybridization",
    subtitle: "trigonal planar",
    description: "Three electron domains with one unhybridized p orbital, central to carbonyls, alkenes, and aromatic rings.",
    curriculum: ["Organic Chemistry I", "General Chemistry"],
    difficulty: "Beginner",
    tags: ["trigonal planar", "p orbital", "120 degrees"],
    actions: [action("Open Hybridization Lesson", "/interactive-learning?topic=hybridization&compound=ethene")],
  }),
  node({
    id: "orbital:p-orbital",
    type: "orbital",
    label: "p Orbital",
    subtitle: "side-by-side overlap",
    description: "Unhybridized p orbital that forms pi bonds and conjugated systems.",
    curriculum: ["Organic Chemistry I", "General Chemistry"],
    difficulty: "Beginner",
    tags: ["pi bond", "orbital", "conjugation"],
    actions: [action("Open Sigma/Pi Lesson", "/interactive-learning?topic=sigma-pi&compound=ethene")],
  }),
  node({
    id: "concept:conjugation",
    type: "conjugation",
    label: "Conjugation",
    subtitle: "continuous p orbitals",
    description: "Alternating p orbitals allow electron delocalization across multiple atoms.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["resonance", "delocalization", "pi system"],
    actions: [action("Open Conjugation Lesson", "/interactive-learning/conjugation?compound=benzene")],
  }),
  node({
    id: "concept:resonance",
    type: "conjugation",
    label: "Resonance",
    subtitle: "electron delocalization",
    description: "Multiple valid electron arrangements describe one delocalized structure.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["curved arrows", "delocalization", "formal charge"],
    actions: [action("Open Resonance Lesson", "/interactive-learning/conjugation?compound=benzene&focus=resonance")],
  }),
  node({
    id: "concept:huckel-rule",
    type: "aromaticity",
    label: "Huckel Rule",
    subtitle: "4n + 2",
    description: "Aromatic systems have cyclic continuous p orbitals and 4n+2 pi electrons.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["aromaticity", "4n+2", "pi electrons"],
    actions: [action("Open Aromaticity Lesson", "/interactive-learning/conjugation?compound=benzene&focus=aromaticity")],
  }),
  node({
    id: "concept:aromaticity",
    type: "aromaticity",
    label: "Aromaticity",
    subtitle: "stable cyclic conjugation",
    description: "Extra stability from cyclic, planar, continuous p-orbital overlap with a Huckel electron count.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["benzene", "Huckel", "ring current"],
    actions: [action("Practice Aromaticity", practice("Aromaticity"))],
  }),
  node({
    id: "mo:homo",
    type: "homo",
    label: "HOMO",
    subtitle: "highest occupied molecular orbital",
    description: "The highest-energy occupied orbital explains electron donation and reactivity.",
    curriculum: ["General Chemistry", "Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["orbital", "reactivity", "electron donor"],
    actions: [action("Open MO Lesson", "/interactive-learning?topic=mo&molecule=O2")],
  }),
  node({
    id: "mo:lumo",
    type: "lumo",
    label: "LUMO",
    subtitle: "lowest unoccupied molecular orbital",
    description: "The lowest empty orbital explains electron acceptance and nucleophilic attack destinations.",
    curriculum: ["General Chemistry", "Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["orbital", "reactivity", "electron acceptor"],
    actions: [action("Open MO Lesson", "/interactive-learning?topic=mo&molecule=O2")],
  }),
  node({
    id: "spectroscopy:ir-carbonyl",
    type: "irPeak",
    label: "IR Carbonyl Peak",
    subtitle: "near 1715 cm^-1",
    description: "Strong C=O absorption used to detect ketones, aldehydes, acids, esters, and amides.",
    curriculum: ["Spectroscopy", "Organic Chemistry I"],
    difficulty: "Beginner",
    tags: ["IR", "1715", "carbonyl"],
    actions: [action("Open Spectroscopy Explorer", "/spectroscopy-explorer?topic=ir-carbonyl"), action("Practice IR", practice("IR Spectroscopy"))],
  }),
  node({
    id: "spectroscopy:aromatic-h-nmr",
    type: "nmrPeak",
    label: "Aromatic 1H NMR",
    subtitle: "about 6.5-8 ppm",
    description: "Aromatic protons appear downfield because ring currents deshield them.",
    curriculum: ["Spectroscopy", "Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["NMR", "aromatic", "benzene"],
    actions: [action("Open Spectroscopy Explorer", "/spectroscopy-explorer?topic=nmr-aromatic")],
  }),
  node({
    id: "spectroscopy:molecular-ion",
    type: "massFragment",
    label: "Molecular Ion",
    subtitle: "M+ peak",
    description: "Mass spectrometry peak corresponding to the intact molecular ion.",
    curriculum: ["Spectroscopy"],
    difficulty: "Beginner",
    tags: ["mass spec", "M+", "molecular weight"],
    actions: [action("Open Spectroscopy Explorer", "/spectroscopy-explorer?topic=mass-molecular-ion")],
  }),
  node({
    id: "mechanism:benzene-bromination",
    type: "mechanism",
    label: "Benzene Bromination",
    subtitle: "EAS",
    description: "Electrophilic aromatic substitution where aromaticity is lost in the sigma complex and restored after deprotonation.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["EAS", "benzene", "bromination"],
    actions: [action("Open Mechanism Simulator", mechanismSimulatorHref({ reaction: "benzene-bromination", compound: "benzene" })), action("Practice Mechanisms", practice("Organic Mechanisms"))],
  }),
  node({
    id: "mechanism:sn2",
    type: "mechanism",
    label: "SN2",
    subtitle: "concerted substitution",
    description: "Backside nucleophilic attack and leaving-group departure in one elementary step.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["substitution", "nucleophile", "leaving group"],
    actions: [action("Open Mechanism Simulator", mechanismSimulatorHref({ reaction: "sn2" })), action("Practice SN2", practice("Organic Mechanisms"))],
  }),
  node({
    id: "mechanism:carbonyl-addition",
    type: "mechanism",
    label: "Nucleophilic Addition",
    subtitle: "carbonyl addition",
    description: "Nucleophile attacks the carbonyl carbon while C=O pi electrons move to oxygen.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["carbonyl", "nucleophile", "addition"],
    actions: [action("Open Mechanism Simulator", mechanismSimulatorHref({ reaction: "carbonyl-addition", compound: "acetone" }))],
  }),
  node({
    id: "reaction:benzene-bromination",
    type: "reaction",
    label: "Benzene + Br2",
    subtitle: "FeBr3 catalyst",
    description: "Reaction condition context for electrophilic aromatic bromination.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["reaction", "bromination", "EAS"],
    actions: [action("Open Reaction Database", "/reaction-database?reaction=benzene-bromination")],
  }),
  node({
    id: "lab:tlc",
    type: "labTechnique",
    label: "TLC",
    subtitle: "thin-layer chromatography",
    description: "Lab technique for monitoring reaction progress and comparing product polarity.",
    curriculum: ["Laboratory Skills", "Organic Chemistry I"],
    difficulty: "Beginner",
    tags: ["lab", "chromatography", "Rf"],
    actions: [action("Open Lab Explorer", "/lab-explorer?technique=tlc")],
  }),
  node({
    id: "formula:ph",
    type: "formula",
    label: "pH Formula",
    subtitle: "pH = -log[H+]",
    description: "Acid/base calculation formula connected to lab titration and equilibrium topics.",
    curriculum: ["General Chemistry", "Laboratory Skills"],
    difficulty: "Beginner",
    tags: ["formula", "acid", "base", "pH"],
    actions: [action("Open Formula Sheet", "/formula-sheet?formula=ph"), action("Open Solver", "/chemistry-solver?module=ph")],
  }),
  node({
    id: "curriculum:organic-i",
    type: "curriculumTopic",
    label: "Organic Chemistry I",
    subtitle: "guided map",
    description: "Curriculum slice covering bonding, functional groups, spectroscopy, and mechanisms.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Beginner",
    tags: ["curriculum", "organic"],
    actions: [action("Open Curriculum", "/curriculum?topic=organic-mechanisms")],
  }),
  node({
    id: "practice:aromaticity",
    type: "practice",
    label: "Aromaticity Practice",
    subtitle: "database questions",
    description: "Practice questions for identifying aromatic systems, Huckel counts, and resonance.",
    curriculum: ["Organic Chemistry I"],
    difficulty: "Intermediate",
    tags: ["practice", "aromaticity"],
    actions: [action("Practice This", practice("Aromaticity")), action("Generate Exam Set", exam("Aromaticity"))],
  }),
]

export const KNOWLEDGE_GRAPH_EDGES: ChemistryKnowledgeEdge[] = [
  edge("compound:benzene", "functional-group:arene", "contains", "contains arene"),
  edge("compound:benzene", "hybridization:sp2", "requires", "six sp2 carbons"),
  edge("hybridization:sp2", "orbital:p-orbital", "explains", "leaves p orbital"),
  edge("orbital:p-orbital", "concept:conjugation", "prerequisiteFor", "enables conjugation"),
  edge("concept:conjugation", "concept:resonance", "explains", "delocalizes electrons"),
  edge("concept:resonance", "concept:huckel-rule", "requires", "needs electron count"),
  edge("concept:huckel-rule", "concept:aromaticity", "explains", "classifies aromaticity"),
  edge("concept:aromaticity", "compound:benzene", "exampleOf", "benzene is archetype"),
  edge("compound:benzene", "spectroscopy:aromatic-h-nmr", "measuredBy", "aromatic H NMR"),
  edge("compound:benzene", "mechanism:benzene-bromination", "participatesIn", "undergoes EAS"),
  edge("reaction:benzene-bromination", "mechanism:benzene-bromination", "usesMechanism", "uses mechanism"),
  edge("mechanism:benzene-bromination", "concept:aromaticity", "requires", "aromaticity restored"),
  edge("mechanism:benzene-bromination", "practice:aromaticity", "practicedIn", "mechanism practice"),
  edge("compound:phenol", "compound:benzene", "similarTo", "benzene derivative"),
  edge("compound:aniline", "compound:benzene", "similarTo", "benzene derivative"),
  edge("compound:toluene", "compound:benzene", "similarTo", "benzene derivative"),
  edge("compound:nitrobenzene", "compound:benzene", "similarTo", "benzene derivative"),
  edge("compound:acetone", "functional-group:carbonyl", "contains", "contains C=O"),
  edge("functional-group:carbonyl", "hybridization:sp2", "requires", "carbonyl carbon is sp2"),
  edge("functional-group:carbonyl", "spectroscopy:ir-carbonyl", "detectedBy", "strong IR peak"),
  edge("functional-group:carbonyl", "mechanism:carbonyl-addition", "participatesIn", "undergoes addition"),
  edge("mechanism:carbonyl-addition", "mo:lumo", "requires", "attack into pi-star LUMO"),
  edge("mo:homo", "mo:lumo", "explains", "frontier orbital gap"),
  edge("compound:ethanol", "functional-group:alcohol", "contains", "contains OH"),
  edge("functional-group:alcohol", "lab:tlc", "usedIn", "polarity affects TLC"),
  edge("formula:ph", "lab:tlc", "similarTo", "both support lab interpretation"),
  edge("curriculum:organic-i", "functional-group:carbonyl", "contains", "covers carbonyls"),
  edge("curriculum:organic-i", "functional-group:arene", "contains", "covers arenes"),
  edge("curriculum:organic-i", "mechanism:sn2", "contains", "covers substitution"),
  edge("mechanism:sn2", "practice:aromaticity", "practicedIn", "same practice engine"),
  edge("compound:benzene", "mo:homo", "visualizedBy", "frontier orbitals"),
  edge("compound:benzene", "mo:lumo", "visualizedBy", "frontier orbitals"),
  edge("spectroscopy:molecular-ion", "compound:acetone", "measuredBy", "molecular ion supports identity"),
]

export const KNOWLEDGE_GRAPH = {
  nodes: KNOWLEDGE_GRAPH_NODES,
  edges: KNOWLEDGE_GRAPH_EDGES,
}
