import type { LabTechniqueRecord } from "./lab-types"

function lab(record: LabTechniqueRecord): LabTechniqueRecord {
  return record
}

export const LAB_TECHNIQUES: LabTechniqueRecord[] = [
  lab({
    id: "titration",
    name: "Titration",
    category: "Volumetric Analysis",
    difficulty: "Intermediate",
    purpose: "Determine an unknown concentration by reacting a measured analyte with a standard solution.",
    equipment: ["burette", "pipette", "conical flask", "indicator", "volumetric flask", "white tile"],
    procedure: [
      "Rinse the burette with the titrant and fill it, removing air bubbles from the tip.",
      "Use a volumetric pipette to transfer a known volume of analyte into a conical flask.",
      "Add a suitable indicator and place the flask on a white tile.",
      "Record the initial burette reading at eye level from the bottom of the meniscus.",
      "Titrate while swirling until the endpoint color change persists.",
      "Record the final burette reading and repeat until concordant titres are obtained.",
    ],
    commonMistakes: [
      "Reading the meniscus from above or below eye level",
      "Forgetting to rinse the burette with titrant",
      "Overshooting the endpoint",
      "Using rough titres in the final average",
    ],
    safetyNotes: ["Wear splash goggles", "Neutralize acid/base spills promptly", "Clamp the burette securely"],
    examClues: ["concordant titres", "indicator endpoint", "standard solution", "mean titre"],
    labReportChecklist: ["balanced equation", "titre table", "mean concordant titre", "moles calculation", "uncertainty comment"],
    related: {
      formulas: ["solutions-molarity", "stoichiometry-limiting-reagent"],
      reactions: ["rxn-neutralization-hcl-naoh"],
      solverModules: ["molarity", "stoichiometry"],
      practiceTopics: ["Lab Skills", "Acids and Bases", "Stoichiometry"],
    },
    aliases: ["acid-base titration", "volumetric analysis", "titre", "endpoint"],
  }),
  lab({
    id: "pipetting",
    name: "Pipetting",
    category: "Volumetric Analysis",
    difficulty: "Introductory",
    purpose: "Transfer an accurate fixed volume of liquid using a volumetric pipette.",
    equipment: ["volumetric pipette", "pipette filler", "beaker", "conical flask"],
    procedure: [
      "Rinse the pipette with the solution being transferred.",
      "Use a pipette filler to draw liquid above the calibration mark.",
      "Lower the meniscus to the mark at eye level.",
      "Drain into the receiving flask with the tip touching the inner wall.",
      "Allow the pipette to drain naturally without blowing out the final drop unless instructed.",
    ],
    commonMistakes: ["Mouth pipetting", "Blowing out a volumetric pipette", "Not rinsing with solution", "Viewing the mark at an angle"],
    safetyNotes: ["Never mouth pipette", "Use a pipette filler", "Clean spills immediately"],
    examClues: ["fixed volume", "volumetric pipette", "transfer aliquot", "calibration mark"],
    labReportChecklist: ["pipette volume", "rinsing method", "uncertainty of pipette", "solution identity"],
    related: {
      formulas: ["solutions-molarity"],
      reactions: [],
      solverModules: ["molarity"],
      practiceTopics: ["Lab Skills", "Stoichiometry"],
    },
    aliases: ["volumetric pipette", "aliquot", "pipette filler"],
  }),
  lab({
    id: "burette-reading",
    name: "Burette Reading",
    category: "Measurement",
    difficulty: "Introductory",
    purpose: "Measure delivered volume accurately from initial and final burette readings.",
    equipment: ["burette", "clamp stand", "white card"],
    procedure: [
      "Ensure the burette is vertical and the tip is filled with solution.",
      "Read the bottom of the meniscus at eye level.",
      "Record values to the appropriate decimal place, usually nearest 0.05 cm3.",
      "Subtract the initial reading from the final reading to find the titre.",
    ],
    commonMistakes: ["Reading from the top of the meniscus", "Parallax error", "Reversing final and initial readings", "Forgetting units"],
    safetyNotes: ["Clamp glassware securely", "Avoid leaning over corrosive solutions"],
    examClues: ["initial reading", "final reading", "titre", "parallax"],
    labReportChecklist: ["initial reading", "final reading", "titre calculation", "unit and uncertainty"],
    related: {
      formulas: ["solutions-molarity"],
      reactions: ["rxn-neutralization-hcl-naoh"],
      solverModules: ["molarity"],
      practiceTopics: ["Lab Skills", "Acids and Bases"],
    },
    aliases: ["buret reading", "titre reading", "burette"],
  }),
  lab({
    id: "meniscus-reading",
    name: "Meniscus Reading",
    category: "Measurement",
    difficulty: "Introductory",
    purpose: "Read liquid volume consistently at the correct part of the curved liquid surface.",
    equipment: ["measuring cylinder", "burette", "volumetric flask", "pipette"],
    procedure: [
      "Place the vessel upright on a level surface.",
      "Bring your eye level with the liquid mark.",
      "Read the bottom of a concave meniscus for aqueous solutions.",
      "Record the volume with appropriate precision.",
    ],
    commonMistakes: ["Parallax error", "Reading from the top of the meniscus", "Using a measuring cylinder when a volumetric pipette is required"],
    safetyNotes: ["Keep glassware stable", "Use appropriate PPE for the liquid"],
    examClues: ["bottom of meniscus", "eye level", "parallax error", "volume uncertainty"],
    labReportChecklist: ["glassware type", "reading precision", "meniscus position", "uncertainty"],
    related: {
      formulas: ["solutions-molarity"],
      reactions: [],
      solverModules: ["molarity"],
      practiceTopics: ["Lab Skills"],
    },
    aliases: ["meniscus", "parallax", "volume reading"],
  }),
  lab({
    id: "filtration",
    name: "Filtration",
    category: "Separation",
    difficulty: "Introductory",
    purpose: "Separate an insoluble solid from a liquid using filter paper or a vacuum setup.",
    equipment: ["filter funnel", "filter paper", "beaker", "conical flask", "Buchner funnel", "vacuum flask"],
    procedure: [
      "Fold and wet filter paper so it seals against the funnel.",
      "Pour the mixture slowly down a glass rod into the funnel.",
      "Collect the filtrate in a clean vessel.",
      "Wash the residue if needed and allow it to dry.",
    ],
    commonMistakes: ["Overfilling the funnel", "Tearing the filter paper", "Not washing residue", "Calling the filtrate the residue"],
    safetyNotes: ["Use vacuum glassware only if it is designed for reduced pressure", "Dispose of solids appropriately"],
    examClues: ["insoluble precipitate", "filtrate", "residue", "separate solid from liquid"],
    labReportChecklist: ["identity of residue", "identity of filtrate", "washing step", "drying method"],
    related: {
      formulas: [],
      reactions: ["rxn-precip-agcl"],
      solverModules: ["stoichiometry"],
      practiceTopics: ["Lab Skills", "Precipitation"],
    },
    aliases: ["gravity filtration", "vacuum filtration", "residue", "filtrate"],
  }),
  lab({
    id: "recrystallization",
    name: "Recrystallization",
    category: "Organic Techniques",
    difficulty: "Intermediate",
    purpose: "Purify a crystalline solid by dissolving it hot and crystallizing it slowly on cooling.",
    equipment: ["Erlenmeyer flask", "hot plate", "filter funnel", "ice bath", "Buchner funnel", "watch glass"],
    procedure: [
      "Choose a solvent where the solid is soluble hot but poorly soluble cold.",
      "Dissolve the impure solid in minimum hot solvent.",
      "Hot filter if insoluble impurities are present.",
      "Cool slowly, then use an ice bath to maximize crystallization.",
      "Collect crystals by vacuum filtration and dry them.",
    ],
    commonMistakes: ["Using too much solvent", "Cooling too quickly", "Skipping hot filtration when insoluble impurities remain", "Not drying crystals before weighing"],
    safetyNotes: ["Avoid open flames with flammable solvents", "Use heat-resistant gloves", "Work in a hood if solvent vapors are harmful"],
    examClues: ["purify solid", "minimum hot solvent", "crystals form on cooling", "melting point purity check"],
    labReportChecklist: ["solvent choice", "mass before/after", "percent recovery", "melting point range", "purity discussion"],
    related: {
      formulas: ["stoichiometry-percent-yield"],
      reactions: [],
      solverModules: ["percent-yield"],
      practiceTopics: ["Lab Skills", "Organic Reactions"],
    },
    aliases: ["crystallization", "purify solid", "hot filtration"],
  }),
  lab({
    id: "distillation",
    name: "Distillation",
    category: "Separation",
    difficulty: "Intermediate",
    purpose: "Separate liquids or remove solvent based on differences in boiling point.",
    equipment: ["round-bottom flask", "condenser", "thermometer", "receiver", "heat source", "anti-bumping granules"],
    procedure: [
      "Assemble glassware with secure clamps and water flowing through the condenser.",
      "Add anti-bumping granules before heating.",
      "Heat gently so vapor condenses and collects in the receiver.",
      "Monitor the thermometer at the still head.",
      "Collect the fraction in the desired boiling range.",
    ],
    commonMistakes: ["Sealing a closed system", "Forgetting condenser water", "Placing thermometer bulb incorrectly", "Heating too strongly"],
    safetyNotes: ["Never distill to dryness", "Keep flammable solvents away from flames", "Do not seal the apparatus"],
    examClues: ["different boiling points", "collect distillate", "condenser", "fraction"],
    labReportChecklist: ["boiling range", "distillate identity", "apparatus diagram", "safety controls"],
    related: {
      formulas: [],
      reactions: ["rxn-organic-ethanol-oxidation"],
      solverModules: [],
      practiceTopics: ["Lab Skills", "Organic Reactions"],
    },
    aliases: ["simple distillation", "fractional distillation", "distillate", "condenser"],
  }),
  lab({
    id: "extraction",
    name: "Extraction",
    category: "Organic Techniques",
    difficulty: "Intermediate",
    purpose: "Transfer a compound between immiscible layers based on solubility or acid-base behavior.",
    equipment: ["separatory funnel", "stopper", "ring stand", "organic solvent", "aqueous wash", "drying agent"],
    procedure: [
      "Add the mixture and extraction solvent to a separatory funnel.",
      "Stopper, invert, and vent frequently away from people.",
      "Allow layers to separate fully.",
      "Identify and drain the lower layer carefully.",
      "Repeat washes if needed and dry the organic layer.",
    ],
    commonMistakes: ["Forgetting to vent", "Discarding the wrong layer", "Shaking emulsions too aggressively", "Not removing drying agent"],
    safetyNotes: ["Vent pressure frequently", "Point the funnel away from people", "Use a hood for volatile solvents"],
    examClues: ["immiscible layers", "separatory funnel", "organic layer", "aqueous layer", "partition"],
    labReportChecklist: ["layer identity", "solvent used", "wash steps", "drying agent", "recovery"],
    related: {
      formulas: [],
      reactions: [],
      solverModules: [],
      practiceTopics: ["Lab Skills", "Organic Reactions"],
    },
    aliases: ["separatory funnel", "liquid-liquid extraction", "organic layer", "aqueous layer"],
  }),
  lab({
    id: "tlc",
    name: "Thin-Layer Chromatography",
    category: "Organic Techniques",
    difficulty: "Intermediate",
    purpose: "Compare components of a mixture by how far they travel on a stationary phase relative to the solvent front.",
    equipment: ["TLC plate", "capillary spotter", "developing chamber", "solvent", "UV lamp", "pencil"],
    procedure: [
      "Draw a pencil baseline near the bottom of the plate.",
      "Spot small concentrated samples on the baseline.",
      "Place the plate in a chamber with solvent below the baseline.",
      "Remove the plate before the solvent reaches the top.",
      "Mark the solvent front and visualize spots.",
      "Calculate Rf values if needed.",
    ],
    commonMistakes: ["Using pen on the plate", "Submerging spots in solvent", "Making spots too large", "Forgetting to mark the solvent front"],
    safetyNotes: ["Use solvent in a hood", "Avoid looking directly at UV light", "Wear gloves when handling plates"],
    examClues: ["Rf value", "stationary phase", "solvent front", "purity check", "reaction monitoring"],
    labReportChecklist: ["solvent system", "spot labels", "solvent front distance", "spot distance", "Rf values"],
    related: {
      formulas: [],
      reactions: ["rxn-organic-ethanol-ethanoic-acid"],
      solverModules: [],
      practiceTopics: ["Lab Skills", "Organic Reactions"],
    },
    aliases: ["thin layer chromatography", "chromatography", "rf value", "tlc plate"],
  }),
  lab({
    id: "ir-sample-prep",
    name: "IR Sample Preparation",
    category: "Spectroscopy Prep",
    difficulty: "Intermediate",
    purpose: "Prepare a clean sample for infrared spectroscopy so functional-group peaks can be interpreted.",
    equipment: ["ATR crystal", "IR plates", "spatula", "solvent", "lint-free wipe"],
    procedure: [
      "Clean the ATR crystal or plates before use.",
      "Apply a small amount of dry sample evenly.",
      "Ensure good contact with the ATR crystal or form a thin film.",
      "Collect background and sample scans.",
      "Clean the accessory after analysis.",
    ],
    commonMistakes: ["Using wet samples when O-H evidence matters", "Leaving residue from a previous sample", "Applying too much sample", "Ignoring background scan"],
    safetyNotes: ["Check solvent hazards", "Avoid scratching ATR crystal", "Wear gloves for unknown samples"],
    examClues: ["functional group identification", "background scan", "ATR", "thin film", "dry sample"],
    labReportChecklist: ["sample state", "preparation method", "key peak assignments", "contamination check"],
    related: {
      formulas: [],
      reactions: [],
      solverModules: [],
      practiceTopics: ["Lab Skills", "Spectroscopy", "IR Spectroscopy"],
    },
    aliases: ["infrared sample prep", "atr", "ir prep", "ir spectroscopy"],
  }),
  lab({
    id: "nmr-sample-prep",
    name: "NMR Sample Preparation",
    category: "Spectroscopy Prep",
    difficulty: "Intermediate",
    purpose: "Prepare a clean NMR tube sample using deuterated solvent for interpretable NMR spectra.",
    equipment: ["NMR tube", "deuterated solvent", "pipette", "sample vial", "cap"],
    procedure: [
      "Dissolve a small amount of sample in a suitable deuterated solvent.",
      "Transfer solution into a clean NMR tube to the recommended fill height.",
      "Cap the tube and wipe the outside clean.",
      "Check that no solid particles or bubbles interfere with the sample column.",
      "Record solvent and concentration notes.",
    ],
    commonMistakes: ["Using too much sample", "Using non-deuterated solvent", "Dirty or chipped NMR tube", "Incorrect fill height"],
    safetyNotes: ["Handle deuterated solvents with care", "Avoid broken glass", "Use a hood for volatile solvents"],
    examClues: ["deuterated solvent", "chemical shift", "integration", "splitting", "equivalent hydrogens"],
    labReportChecklist: ["solvent", "sample concentration", "key shifts", "integration", "splitting assignments"],
    related: {
      formulas: [],
      reactions: [],
      solverModules: [],
      practiceTopics: ["Lab Skills", "NMR Spectroscopy", "Spectroscopy"],
    },
    aliases: ["nmr prep", "nmr tube", "deuterated solvent", "proton nmr"],
  }),
  lab({
    id: "calorimetry",
    name: "Calorimetry",
    category: "Thermochemistry",
    difficulty: "Intermediate",
    purpose: "Measure heat transfer from temperature change and calculate q or enthalpy change.",
    equipment: ["coffee-cup calorimeter", "thermometer", "balance", "stirrer", "insulated cup"],
    procedure: [
      "Measure masses or volumes of reactants.",
      "Record initial temperature.",
      "Mix reactants in an insulated calorimeter.",
      "Stir and record the maximum or minimum temperature.",
      "Calculate delta T and use q = mc delta T.",
    ],
    commonMistakes: ["Using Celsius temperature instead of temperature change incorrectly", "Wrong sign for exothermic/endothermic", "Ignoring heat loss", "Forgetting units for specific heat"],
    safetyNotes: ["Avoid burns from hot solutions", "Use goggles for reacting chemicals", "Dispose of reaction mixtures appropriately"],
    examClues: ["temperature change", "specific heat capacity", "q = mc delta T", "enthalpy per mole"],
    labReportChecklist: ["mass", "specific heat", "initial/final temperature", "delta T", "q calculation", "sign convention"],
    related: {
      formulas: ["thermochemistry-calorimetry", "thermochemistry-enthalpy-per-mole"],
      reactions: ["rxn-neutralization-hcl-naoh"],
      solverModules: ["calorimetry"],
      practiceTopics: ["Lab Skills", "Thermodynamics", "Chemistry Calculations"],
    },
    aliases: ["coffee cup calorimetry", "q=mc", "enthalpy lab", "temperature change"],
  }),
  lab({
    id: "safety-symbols",
    name: "Safety Symbols",
    category: "Safety",
    difficulty: "Introductory",
    purpose: "Recognize hazard pictograms and choose safe handling procedures.",
    equipment: ["GHS labels", "SDS", "chemical bottle labels"],
    procedure: [
      "Read the label before using any chemical.",
      "Identify hazard pictograms and signal words.",
      "Check PPE and handling requirements.",
      "Use the SDS for detailed hazards, storage, and disposal.",
    ],
    commonMistakes: ["Ignoring pictograms", "Assuming dilute means harmless", "Mixing incompatible waste", "Not reading the SDS"],
    safetyNotes: ["Treat unknown chemicals as hazardous", "Follow local lab instructions", "Report spills and exposure immediately"],
    examClues: ["corrosive", "flammable", "oxidizer", "toxic", "irritant", "environmental hazard"],
    labReportChecklist: ["hazards identified", "risk controls", "PPE", "waste stream", "emergency notes"],
    related: {
      formulas: [],
      reactions: [],
      solverModules: [],
      practiceTopics: ["Lab Skills"],
    },
    aliases: ["ghs", "hazard pictograms", "safety labels", "sds"],
  }),
  lab({
    id: "ppe",
    name: "Personal Protective Equipment",
    category: "Safety",
    difficulty: "Introductory",
    purpose: "Choose and use protective equipment to reduce exposure risk.",
    equipment: ["splash goggles", "lab coat", "nitrile gloves", "closed-toe shoes", "fume hood"],
    procedure: [
      "Put on goggles, lab coat, and closed-toe shoes before work begins.",
      "Choose gloves appropriate for the chemicals being used.",
      "Tie back long hair and secure loose clothing.",
      "Work in a hood when fumes or volatile solvents are involved.",
      "Remove contaminated gloves before touching shared surfaces.",
    ],
    commonMistakes: ["Wearing gloves outside the lab", "Using goggles as a headband", "Choosing PPE after a spill", "Touching phone or face with contaminated gloves"],
    safetyNotes: ["PPE reduces risk but does not replace careful technique", "Report damaged PPE", "Wash hands after lab"],
    examClues: ["splash risk", "volatile solvent", "corrosive chemical", "contaminated gloves"],
    labReportChecklist: ["PPE listed", "risk control explained", "hood use justified", "exposure response"],
    related: {
      formulas: [],
      reactions: [],
      solverModules: [],
      practiceTopics: ["Lab Skills"],
    },
    aliases: ["goggles", "gloves", "lab coat", "personal protective equipment"],
  }),
  lab({
    id: "waste-disposal",
    name: "Waste Disposal",
    category: "Safety",
    difficulty: "Introductory",
    purpose: "Dispose of chemical and glass waste in the correct stream to avoid hazards and contamination.",
    equipment: ["aqueous waste container", "organic waste container", "solid waste container", "broken glass bin", "spill kit"],
    procedure: [
      "Identify whether waste is aqueous, organic, solid, sharps, or special hazard.",
      "Use the labeled container assigned by the lab.",
      "Do not mix incompatible waste streams.",
      "Cap containers after use and report full containers.",
      "Dispose of broken glass only in approved glass bins.",
    ],
    commonMistakes: ["Pouring organic solvent down the sink", "Mixing acid and base waste without instruction", "Putting broken glass in regular trash", "Leaving waste containers open"],
    safetyNotes: ["Ask if unsure", "Do not smell waste containers", "Use spill response procedures for leaks"],
    examClues: ["organic waste", "aqueous waste", "broken glass", "heavy metal salts", "incompatible chemicals"],
    labReportChecklist: ["waste stream", "hazard reason", "neutralization if instructed", "spill response"],
    related: {
      formulas: [],
      reactions: [],
      solverModules: [],
      practiceTopics: ["Lab Skills"],
    },
    aliases: ["chemical waste", "organic waste", "aqueous waste", "broken glass"],
  }),
  lab({
    id: "common-lab-glassware",
    name: "Common Lab Glassware",
    category: "Glassware",
    difficulty: "Introductory",
    purpose: "Identify common glassware and choose the right item for measuring, mixing, heating, or transfer.",
    equipment: ["beaker", "Erlenmeyer flask", "volumetric flask", "graduated cylinder", "burette", "pipette", "watch glass"],
    procedure: [
      "Use volumetric glassware for accurate fixed volumes.",
      "Use beakers and Erlenmeyer flasks for mixing, not high-precision measurement.",
      "Use graduated cylinders for approximate measured volumes.",
      "Use watch glasses for evaporation or covering beakers.",
    ],
    commonMistakes: ["Using beakers for precise volume", "Confusing volumetric flask and conical flask", "Heating sealed glassware", "Using chipped glassware"],
    safetyNotes: ["Inspect for cracks", "Use tongs or heat gloves for hot glass", "Do not heat volumetric glassware"],
    examClues: ["accurate volume", "rough volume", "mixing flask", "standard solution", "calibrated mark"],
    labReportChecklist: ["glassware choice", "accuracy reason", "uncertainty if measured", "clean/dry condition"],
    related: {
      formulas: ["solutions-molarity"],
      reactions: [],
      solverModules: ["molarity"],
      practiceTopics: ["Lab Skills"],
    },
    aliases: ["glassware", "beaker", "conical flask", "volumetric flask", "graduated cylinder"],
  }),
]

