import type {
  CarbonNmrSignal,
  CompoundSpectroscopyProfile,
  MassSpecSignal,
  ProtonNmrSignal,
  ReactionSpectralChange,
  SpectroscopySignalRecord,
} from "./spectroscopy-types"

function signal(record: SpectroscopySignalRecord): SpectroscopySignalRecord {
  return record
}

export const SPECTROSCOPY_SIGNAL_RECORDS: SpectroscopySignalRecord[] = [
  signal({
    id: "ir-oh-alcohol",
    category: "IR",
    signal: "O-H stretch",
    range: "3200-3600 cm^-1",
    functionalGroup: "Alcohol",
    foundIn: ["alcohols", "phenols"],
    explanation: "Hydrogen bonding makes most alcohol O-H absorptions broad and strong.",
    examClues: ["Broad strong band around 3300 cm^-1", "Often appears with a C-O stretch near 1000-1300 cm^-1"],
    aliases: ["oh", "o-h", "alcohol", "hydroxyl", "ir-oh"],
  }),
  signal({
    id: "ir-oh-carboxylic-acid",
    category: "IR",
    signal: "acid O-H stretch",
    range: "2500-3300 cm^-1",
    functionalGroup: "Carboxylic Acid",
    foundIn: ["carboxylic acids"],
    explanation: "Carboxylic acid O-H absorptions are extremely broad and often overlap the C-H region.",
    examClues: ["Very broad O-H from 2500 to 3300 cm^-1", "Usually paired with a strong carbonyl"],
    aliases: ["acid oh", "cooh", "carboxylic acid"],
  }),
  signal({
    id: "ir-nh-amine",
    category: "IR",
    signal: "N-H stretch",
    range: "3300-3500 cm^-1",
    functionalGroup: "Amine",
    foundIn: ["amines", "amides"],
    explanation: "N-H stretches are usually sharper and less broad than alcohol O-H stretches.",
    examClues: ["Primary amines can show two N-H bands", "Secondary amines often show one band"],
    aliases: ["n-h", "nh", "amine", "amide"],
  }),
  signal({
    id: "ir-carbonyl-general",
    category: "IR",
    signal: "C=O stretch",
    range: "1650-1750 cm^-1",
    functionalGroup: "Carbonyl",
    foundIn: ["ketones", "aldehydes", "carboxylic acids", "esters", "amides"],
    explanation: "A strong sharp absorption near 1700 cm^-1 is one of the clearest carbonyl clues.",
    examClues: ["Strong sharp absorption near 1700 cm^-1 usually indicates C=O", "Use nearby clues to decide aldehyde, ketone, acid, ester, or amide"],
    aliases: ["carbonyl", "c=o", "1700", "ir-carbonyl"],
  }),
  signal({
    id: "ir-ketone-carbonyl",
    category: "IR",
    signal: "ketone C=O stretch",
    range: "1705-1725 cm^-1",
    functionalGroup: "Ketone",
    foundIn: ["ketones"],
    explanation: "Ketone carbonyls are strong and sharp, but lack aldehyde C-H and acid O-H clues.",
    examClues: ["Strong C=O near 1715 cm^-1", "No broad acid O-H and no aldehyde C-H doublet"],
    aliases: ["ketone", "propanone", "acetone"],
  }),
  signal({
    id: "ir-aldehyde-carbonyl",
    category: "IR",
    signal: "aldehyde C=O stretch",
    range: "1720-1740 cm^-1",
    functionalGroup: "Aldehyde",
    foundIn: ["aldehydes"],
    explanation: "Aldehydes show a carbonyl plus weak aldehydic C-H peaks.",
    examClues: ["C=O around 1730 cm^-1", "Weak aldehyde C-H bands near 2720-2820 cm^-1"],
    aliases: ["aldehyde", "cho", "ethanal"],
  }),
  signal({
    id: "ir-ester-carbonyl",
    category: "IR",
    signal: "ester C=O stretch",
    range: "1735-1750 cm^-1",
    functionalGroup: "Ester",
    foundIn: ["esters"],
    explanation: "Ester carbonyls usually appear slightly higher than simple ketone carbonyls.",
    examClues: ["Strong C=O above many ketones", "C-O stretch near 1050-1300 cm^-1"],
    aliases: ["ester", "coor", "ethyl ethanoate"],
  }),
  signal({
    id: "ir-alkene-cc",
    category: "IR",
    signal: "C=C stretch",
    range: "1620-1680 cm^-1",
    functionalGroup: "Alkene",
    foundIn: ["alkenes"],
    explanation: "Alkene C=C absorptions are often medium strength and less dominant than carbonyls.",
    examClues: ["C=C around 1650 cm^-1", "sp2 C-H just above 3000 cm^-1"],
    aliases: ["alkene", "c=c", "double bond"],
  }),
  signal({
    id: "ir-alkyne-cc",
    category: "IR",
    signal: "C#C stretch",
    range: "2100-2260 cm^-1",
    functionalGroup: "Alkyne",
    foundIn: ["alkynes"],
    explanation: "Alkyne stretches are in the triple-bond region and may be weak if the alkyne is symmetrical.",
    examClues: ["Triple-bond region near 2200 cm^-1", "Terminal alkyne C-H near 3300 cm^-1"],
    aliases: ["alkyne", "c#c", "c triple c"],
  }),
  signal({
    id: "ir-nitrile-cn",
    category: "IR",
    signal: "C#N stretch",
    range: "2210-2260 cm^-1",
    functionalGroup: "Nitrile",
    foundIn: ["nitriles"],
    explanation: "Nitrile peaks are sharp in the triple-bond region and are commonly tested near 2250 cm^-1.",
    examClues: ["Sharp peak near 2250 cm^-1", "No broad O-H needed for assignment"],
    aliases: ["nitrile", "c#n", "c triple n", "cyano"],
  }),
  signal({
    id: "ir-aromatic-ring",
    category: "IR",
    signal: "aromatic C=C ring stretches",
    range: "1450-1600 cm^-1",
    functionalGroup: "Aromatic",
    foundIn: ["arenes", "benzene derivatives"],
    explanation: "Aromatic rings often show several medium bands in the 1450-1600 cm^-1 region.",
    examClues: ["Multiple ring bands", "Aromatic C-H just above 3000 cm^-1"],
    aliases: ["aromatic", "arene", "benzene"],
  }),
  signal({
    id: "ir-alkane-ch",
    category: "IR",
    signal: "alkane C-H stretch",
    range: "2850-2960 cm^-1",
    functionalGroup: "Alkane",
    foundIn: ["alkanes", "alkyl groups"],
    explanation: "sp3 C-H stretches below 3000 cm^-1 are common in alkyl chains.",
    examClues: ["C-H below 3000 cm^-1", "Usually not diagnostic by itself"],
    aliases: ["alkane", "c-h", "sp3 ch"],
  }),
  signal({
    id: "ir-alcohol-co",
    category: "IR",
    signal: "C-O stretch",
    range: "1000-1300 cm^-1",
    functionalGroup: "Alcohol",
    foundIn: ["alcohols", "esters", "ethers"],
    explanation: "C-O stretching supports an alcohol assignment when paired with broad O-H.",
    examClues: ["Fingerprint-region C-O", "Use with broad O-H to support alcohol"],
    aliases: ["c-o", "alcohol c-o"],
  }),
  signal({
    id: "h-nmr-alkyl-methyl",
    category: "1H NMR",
    signal: "alkyl CH3 protons",
    range: "0.8-1.2 ppm",
    functionalGroup: "Alkyl",
    foundIn: ["alkanes", "alkyl substituents"],
    explanation: "Methyl groups next to carbon usually appear upfield and often integrate to 3H.",
    examClues: ["Integration often 3H", "Triplet if next to CH2"],
    aliases: ["1h", "proton", "methyl", "ch3"],
  }),
  signal({
    id: "h-nmr-alkyl-methylene",
    category: "1H NMR",
    signal: "alkyl CH2 protons",
    range: "1.2-1.8 ppm",
    functionalGroup: "Alkyl",
    foundIn: ["alkanes", "alkyl chains"],
    explanation: "Methylene hydrogens in simple alkyl chains usually integrate to 2H.",
    examClues: ["Integration often 2H", "Quartet when next to CH3 in ethyl groups"],
    aliases: ["methylene", "ch2"],
  }),
  signal({
    id: "h-nmr-alpha-oxygen",
    category: "1H NMR",
    signal: "H on carbon next to O",
    range: "3.3-4.2 ppm",
    functionalGroup: "Alcohol/Ether/Ester",
    foundIn: ["alcohols", "ethers", "esters"],
    explanation: "Electronegative oxygen deshields nearby protons, moving them downfield.",
    examClues: ["CH2 next to oxygen often around 3.5-4.2 ppm", "Common in alcohols and esters"],
    aliases: ["oxygen proton nmr", "ch-o", "ethanol ch2"],
  }),
  signal({
    id: "h-nmr-vinylic",
    category: "1H NMR",
    signal: "vinylic protons",
    range: "4.5-6.5 ppm",
    functionalGroup: "Alkene",
    foundIn: ["alkenes"],
    explanation: "Hydrogens attached to alkene carbons are deshielded by the pi bond.",
    examClues: ["Alkene H around 5-6 ppm", "Often complex splitting"],
    aliases: ["vinylic", "alkene nmr"],
  }),
  signal({
    id: "h-nmr-aromatic",
    category: "1H NMR",
    signal: "aromatic protons",
    range: "6.5-8.5 ppm",
    functionalGroup: "Aromatic",
    foundIn: ["arenes", "benzene derivatives"],
    explanation: "Aromatic ring currents strongly deshield ring hydrogens.",
    examClues: ["Cluster around 7 ppm", "Integration shows number of ring hydrogens"],
    aliases: ["aromatic nmr", "benzene protons"],
  }),
  signal({
    id: "h-nmr-aldehyde",
    category: "1H NMR",
    signal: "aldehyde proton",
    range: "9.0-10.0 ppm",
    functionalGroup: "Aldehyde",
    foundIn: ["aldehydes"],
    explanation: "Aldehyde protons are strongly deshielded and appear far downfield.",
    examClues: ["Peak near 10 ppm", "Usually integrates to 1H"],
    aliases: ["aldehyde proton", "cho nmr"],
  }),
  signal({
    id: "h-nmr-carboxylic-acid",
    category: "1H NMR",
    signal: "carboxylic acid proton",
    range: "10.0-13.0 ppm",
    functionalGroup: "Carboxylic Acid",
    foundIn: ["carboxylic acids"],
    explanation: "Acid protons are broad, exchangeable, and very downfield.",
    examClues: ["Broad acidic proton around 10-13 ppm", "Disappears with D2O exchange in advanced contexts"],
    aliases: ["acid proton", "cooh nmr"],
  }),
  signal({
    id: "h-nmr-integration",
    category: "1H NMR",
    signal: "integration",
    range: "relative area under each signal",
    functionalGroup: "Equivalent Hydrogens",
    foundIn: ["1H NMR spectra"],
    explanation: "Integration compares the number of equivalent hydrogens responsible for each signal.",
    examClues: ["3H often suggests CH3", "2H often suggests CH2", "Ratios may need simplifying"],
    aliases: ["integration", "area", "relative area"],
  }),
  signal({
    id: "h-nmr-splitting",
    category: "1H NMR",
    signal: "splitting pattern",
    range: "n+1 neighboring proton rule",
    functionalGroup: "Multiplicity",
    foundIn: ["1H NMR spectra"],
    explanation: "For simple first-order spectra, neighboring nonequivalent hydrogens split a signal into n+1 peaks.",
    examClues: ["Singlet means no neighboring equivalent hydrogens", "Triplet next to CH2", "Quartet next to CH3"],
    aliases: ["splitting", "multiplicity", "n+1", "singlet", "doublet", "triplet", "quartet"],
  }),
  signal({
    id: "h-nmr-equivalent-hydrogens",
    category: "1H NMR",
    signal: "equivalent hydrogens",
    range: "one signal per proton environment",
    functionalGroup: "Equivalent Hydrogens",
    foundIn: ["1H NMR spectra"],
    explanation: "Hydrogens in the same chemical environment produce one signal in a simplified 1H NMR spectrum.",
    examClues: ["Symmetry reduces the number of signals", "Equivalent hydrogens share the same shift"],
    aliases: ["equivalent hydrogens", "equivalent protons", "proton environments"],
  }),
  signal({
    id: "c-nmr-alkyl",
    category: "13C NMR",
    signal: "alkyl carbon",
    range: "0-50 ppm",
    functionalGroup: "Alkyl",
    foundIn: ["alkanes", "alkyl substituents"],
    explanation: "Saturated alkyl carbons are usually upfield in carbon NMR.",
    examClues: ["Signals below 50 ppm", "More signals mean more distinct carbon environments"],
    aliases: ["13c", "carbon nmr", "alkyl carbon"],
  }),
  signal({
    id: "c-nmr-environment-count",
    category: "13C NMR",
    signal: "carbon environment count",
    range: "one signal per distinct carbon environment",
    functionalGroup: "Carbon Environments",
    foundIn: ["13C NMR spectra"],
    explanation: "The number of 13C NMR signals equals the number of distinct carbon environments in a simplified spectrum.",
    examClues: ["Symmetry reduces carbon signal count", "Equivalent carbons appear as one signal"],
    aliases: ["carbon environments", "13c signals", "signal count"],
  }),
  signal({
    id: "c-nmr-c-o",
    category: "13C NMR",
    signal: "carbon attached to oxygen",
    range: "50-90 ppm",
    functionalGroup: "Alcohol/Ether",
    foundIn: ["alcohols", "ethers", "esters"],
    explanation: "Oxygen deshields attached carbons compared with simple alkyl carbons.",
    examClues: ["C-O carbon around 50-90 ppm", "Common in alcohols and ethers"],
    aliases: ["c-o carbon", "oxygen carbon"],
  }),
  signal({
    id: "c-nmr-alkene-aromatic",
    category: "13C NMR",
    signal: "alkene or aromatic carbon",
    range: "100-150 ppm",
    functionalGroup: "Unsaturated/Aromatic",
    foundIn: ["alkenes", "arenes"],
    explanation: "sp2 carbons appear downfield relative to saturated carbons.",
    examClues: ["100-150 ppm suggests C=C or arene", "Symmetry reduces signal count"],
    aliases: ["sp2 carbon", "aromatic carbon", "alkene carbon"],
  }),
  signal({
    id: "c-nmr-carbonyl-ester-acid",
    category: "13C NMR",
    signal: "ester or acid carbonyl carbon",
    range: "160-185 ppm",
    functionalGroup: "Carboxylic Acid/Ester/Amide",
    foundIn: ["carboxylic acids", "esters", "amides"],
    explanation: "Carboxylic acid and ester carbonyl carbons appear downfield but usually below aldehyde/ketone carbonyls.",
    examClues: ["Carbonyl carbon around 170 ppm", "Pair with IR C=O for structure ID"],
    aliases: ["ester carbonyl carbon", "acid carbonyl carbon"],
  }),
  signal({
    id: "c-nmr-carbonyl-aldehyde-ketone",
    category: "13C NMR",
    signal: "aldehyde or ketone carbonyl carbon",
    range: "190-220 ppm",
    functionalGroup: "Aldehyde/Ketone",
    foundIn: ["aldehydes", "ketones"],
    explanation: "Aldehyde and ketone carbonyl carbons are among the most downfield 13C signals.",
    examClues: ["Signal near 200 ppm", "Strongly supports aldehyde or ketone"],
    aliases: ["ketone carbonyl carbon", "aldehyde carbonyl carbon"],
  }),
  signal({
    id: "ms-molecular-ion",
    category: "Mass Spec",
    signal: "molecular ion peak",
    range: "M+ peak at molecular mass",
    functionalGroup: "Molecular formula",
    foundIn: ["most molecular spectra"],
    explanation: "The molecular ion peak gives the approximate relative formula mass when visible.",
    examClues: ["Highest meaningful m/z can indicate molecular mass", "Some molecules show weak or absent M+ peaks"],
    aliases: ["mass spec", "molecular ion", "m+"],
  }),
  signal({
    id: "ms-base-peak",
    category: "Mass Spec",
    signal: "base peak",
    range: "100% relative abundance",
    functionalGroup: "Fragmentation",
    foundIn: ["mass spectra"],
    explanation: "The base peak is the most intense peak and usually represents the most stable common fragment.",
    examClues: ["Always set to 100% abundance", "Not necessarily the molecular ion"],
    aliases: ["base peak", "fragment peak"],
  }),
  signal({
    id: "ms-fragment-peaks",
    category: "Mass Spec",
    signal: "fragment peaks",
    range: "lower m/z peaks from broken ions",
    functionalGroup: "Fragmentation",
    foundIn: ["mass spectra"],
    explanation: "Fragment peaks come from pieces of the molecular ion and help infer structural parts.",
    examClues: ["Stable fragments can dominate the spectrum", "Fragments are lower m/z than the molecular ion"],
    aliases: ["fragment", "fragment peak", "fragmentation", "lower m/z"],
  }),
  signal({
    id: "ms-bromine-isotope",
    category: "Mass Spec",
    signal: "bromine isotope pattern",
    range: "M and M+2 roughly 1:1",
    functionalGroup: "Brominated compound",
    foundIn: ["bromoalkanes", "aryl bromides"],
    explanation: "Bromine has two common isotopes of similar abundance, producing near-equal M and M+2 peaks.",
    examClues: ["M and M+2 pair about equal height", "Strong clue for one bromine atom"],
    aliases: ["bromine isotope", "br isotope", "m+2"],
  }),
  signal({
    id: "ms-chlorine-isotope",
    category: "Mass Spec",
    signal: "chlorine isotope pattern",
    range: "M and M+2 roughly 3:1",
    functionalGroup: "Chlorinated compound",
    foundIn: ["chloroalkanes", "aryl chlorides"],
    explanation: "Chlorine isotopes produce an M to M+2 pattern close to 3:1 for one chlorine atom.",
    examClues: ["M+2 about one-third of M", "Strong clue for chlorine"],
    aliases: ["chlorine isotope", "cl isotope"],
  }),
]

function h(record: ProtonNmrSignal): ProtonNmrSignal {
  return record
}

function c(record: CarbonNmrSignal): CarbonNmrSignal {
  return record
}

function ms(record: MassSpecSignal): MassSpecSignal {
  return record
}

export const COMPOUND_SPECTROSCOPY_PROFILES: CompoundSpectroscopyProfile[] = [
  {
    id: "ethanol-spectra",
    compoundId: "ethanol",
    compoundName: "Ethanol",
    formula: "C2H6O",
    irSignalIds: ["ir-oh-alcohol", "ir-alcohol-co", "ir-alkane-ch"],
    protonNmr: [
      h({ id: "ethanol-ch3", environment: "CH3", shiftRange: "1.0-1.3 ppm", integration: "3H", splitting: "triplet", explanation: "The methyl group is split by the neighboring CH2." }),
      h({ id: "ethanol-ch2", environment: "CH2 next to O", shiftRange: "3.4-3.8 ppm", integration: "2H", splitting: "quartet", explanation: "Oxygen deshields the CH2 group and the neighboring CH3 gives a quartet." }),
      h({ id: "ethanol-oh", environment: "O-H", shiftRange: "1-5 ppm", integration: "1H", splitting: "broad singlet", explanation: "The alcohol proton is exchangeable and often broad." }),
    ],
    carbonNmr: [
      c({ id: "ethanol-c1", environment: "CH3 carbon", shiftRange: "15-20 ppm", explanation: "Simple alkyl carbon." }),
      c({ id: "ethanol-c2", environment: "CH2-O carbon", shiftRange: "55-65 ppm", explanation: "Carbon attached to oxygen." }),
    ],
    massSpec: [
      ms({ id: "ethanol-m", peak: "M+", mz: "46", explanation: "Molecular ion corresponds to C2H6O." }),
      ms({ id: "ethanol-frag", peak: "fragment", mz: "31", explanation: "Common CH2OH+ fragment." }),
    ],
    notes: "Ethanol is a classic alcohol example: broad O-H in IR, CH3/CH2/OH in 1H NMR, and a molecular ion near m/z 46.",
  },
  {
    id: "propanone-spectra",
    compoundId: "acetone",
    compoundName: "Propanone",
    formula: "C3H6O",
    irSignalIds: ["ir-ketone-carbonyl", "ir-alkane-ch"],
    protonNmr: [
      h({ id: "propanone-ch3", environment: "two equivalent CH3 groups", shiftRange: "2.0-2.3 ppm", integration: "6H", splitting: "singlet", explanation: "Both methyl groups are equivalent and have no neighboring hydrogens across the carbonyl." }),
    ],
    carbonNmr: [
      c({ id: "propanone-carbonyl", environment: "ketone C=O", shiftRange: "200-210 ppm", explanation: "Ketone carbonyl carbon is far downfield." }),
      c({ id: "propanone-methyl", environment: "equivalent CH3 carbons", shiftRange: "25-35 ppm", explanation: "Only one methyl carbon signal due to symmetry." }),
    ],
    massSpec: [
      ms({ id: "propanone-m", peak: "M+", mz: "58", explanation: "Molecular ion corresponds to C3H6O." }),
      ms({ id: "propanone-base", peak: "base peak", mz: "43", explanation: "Acyl fragment is commonly strong." }),
    ],
    notes: "Propanone shows a strong ketone carbonyl and symmetry-reduced NMR signals.",
  },
  {
    id: "ethanal-spectra",
    compoundId: "ethanal",
    compoundName: "Ethanal",
    formula: "C2H4O",
    irSignalIds: ["ir-aldehyde-carbonyl", "ir-alkane-ch"],
    protonNmr: [
      h({ id: "ethanal-cho", environment: "CHO", shiftRange: "9.5-10.0 ppm", integration: "1H", splitting: "quartet", explanation: "The aldehyde proton couples weakly to the methyl group." }),
      h({ id: "ethanal-ch3", environment: "CH3 next to C=O", shiftRange: "2.0-2.4 ppm", integration: "3H", splitting: "doublet", explanation: "The methyl group is deshielded by the carbonyl and split by the aldehyde proton." }),
    ],
    carbonNmr: [
      c({ id: "ethanal-carbonyl", environment: "aldehyde C=O", shiftRange: "190-205 ppm", explanation: "Aldehyde carbonyl carbon is strongly downfield." }),
      c({ id: "ethanal-methyl", environment: "CH3 alpha to C=O", shiftRange: "20-35 ppm", explanation: "Methyl carbon next to a carbonyl." }),
    ],
    massSpec: [ms({ id: "ethanal-m", peak: "M+", mz: "44", explanation: "Molecular ion corresponds to C2H4O." })],
    notes: "Ethanal is identified by a carbonyl plus a proton near 10 ppm.",
  },
  {
    id: "ethanoic-acid-spectra",
    compoundId: "ethanoic-acid",
    compoundName: "Ethanoic Acid",
    formula: "C2H4O2",
    irSignalIds: ["ir-oh-carboxylic-acid", "ir-carbonyl-general", "ir-alkane-ch"],
    protonNmr: [
      h({ id: "ethanoic-acid-acid-h", environment: "COOH", shiftRange: "10-13 ppm", integration: "1H", splitting: "broad singlet", explanation: "The acid proton is broad and exchangeable." }),
      h({ id: "ethanoic-acid-ch3", environment: "CH3 next to C=O", shiftRange: "2.0-2.3 ppm", integration: "3H", splitting: "singlet", explanation: "No neighboring hydrogens on the carbonyl carbon." }),
    ],
    carbonNmr: [
      c({ id: "ethanoic-acid-carbonyl", environment: "acid C=O", shiftRange: "170-180 ppm", explanation: "Carboxylic acid carbonyl carbon." }),
      c({ id: "ethanoic-acid-methyl", environment: "CH3", shiftRange: "18-25 ppm", explanation: "Methyl carbon." }),
    ],
    massSpec: [ms({ id: "ethanoic-acid-m", peak: "M+", mz: "60", explanation: "Molecular ion corresponds to C2H4O2." })],
    notes: "Very broad acid O-H plus carbonyl is the key ethanoic acid clue.",
  },
  {
    id: "ethyl-ethanoate-spectra",
    compoundId: "ethyl-ethanoate",
    compoundName: "Ethyl Ethanoate",
    formula: "C4H8O2",
    irSignalIds: ["ir-ester-carbonyl", "ir-alcohol-co", "ir-alkane-ch"],
    protonNmr: [
      h({ id: "ethyl-ethanoate-o-ch2", environment: "O-CH2", shiftRange: "4.0-4.3 ppm", integration: "2H", splitting: "quartet", explanation: "The CH2 next to oxygen is deshielded." }),
      h({ id: "ethyl-ethanoate-ethyl-ch3", environment: "ethyl CH3", shiftRange: "1.1-1.4 ppm", integration: "3H", splitting: "triplet", explanation: "The methyl group couples to the O-CH2 group." }),
      h({ id: "ethyl-ethanoate-acyl-ch3", environment: "COCH3", shiftRange: "1.9-2.2 ppm", integration: "3H", splitting: "singlet", explanation: "The acyl methyl has no neighboring hydrogens across the carbonyl." }),
    ],
    carbonNmr: [
      c({ id: "ethyl-ethanoate-carbonyl", environment: "ester C=O", shiftRange: "165-175 ppm", explanation: "Ester carbonyl carbon." }),
      c({ id: "ethyl-ethanoate-o-ch2-c", environment: "O-CH2 carbon", shiftRange: "55-65 ppm", explanation: "Carbon attached to oxygen." }),
    ],
    massSpec: [ms({ id: "ethyl-ethanoate-m", peak: "M+", mz: "88", explanation: "Molecular ion corresponds to C4H8O2." })],
    notes: "Ester C=O plus O-CH2 proton signal near 4 ppm is a strong ethyl ester pattern.",
  },
  {
    id: "benzene-spectra",
    compoundId: "benzene",
    compoundName: "Benzene",
    formula: "C6H6",
    irSignalIds: ["ir-aromatic-ring"],
    protonNmr: [
      h({ id: "benzene-h", environment: "six equivalent aromatic H", shiftRange: "7.1-7.4 ppm", integration: "6H", splitting: "singlet", explanation: "All hydrogens are equivalent in benzene." }),
    ],
    carbonNmr: [
      c({ id: "benzene-c", environment: "six equivalent aromatic carbons", shiftRange: "125-130 ppm", explanation: "Symmetry gives one aromatic carbon environment." }),
    ],
    massSpec: [ms({ id: "benzene-m", peak: "M+", mz: "78", explanation: "Molecular ion corresponds to C6H6." })],
    notes: "Benzene is symmetry-rich: one 1H signal and one 13C signal in an idealized spectrum.",
  },
  {
    id: "phenol-spectra",
    compoundId: "phenol",
    compoundName: "Phenol",
    formula: "C6H6O",
    irSignalIds: ["ir-oh-alcohol", "ir-aromatic-ring", "ir-alcohol-co"],
    protonNmr: [
      h({ id: "phenol-aromatic", environment: "aromatic H", shiftRange: "6.6-7.4 ppm", integration: "5H", splitting: "multiplet", explanation: "Monosubstituted benzene ring gives aromatic multiplets." }),
      h({ id: "phenol-oh", environment: "phenolic O-H", shiftRange: "4-7 ppm", integration: "1H", splitting: "broad singlet", explanation: "Phenol O-H is exchangeable and broad." }),
    ],
    carbonNmr: [
      c({ id: "phenol-aromatic-c", environment: "aromatic carbons", shiftRange: "115-160 ppm", explanation: "Aromatic carbons, with the C-O carbon more downfield." }),
    ],
    massSpec: [ms({ id: "phenol-m", peak: "M+", mz: "94", explanation: "Molecular ion corresponds to C6H6O." })],
    notes: "Phenol combines aromatic evidence with an O-H stretch.",
  },
]

export const REACTION_SPECTRAL_CHANGES: ReactionSpectralChange[] = [
  {
    reactionId: "rxn-organic-ethanol-oxidation",
    reactionName: "Alcohol Oxidation",
    reactantClass: "Alcohol",
    productClass: "Aldehyde or Carboxylic Acid",
    irChanges: ["Alcohol O-H may decrease or disappear", "C=O appears near 1700 cm^-1", "Acid O-H appears if oxidation continues to carboxylic acid"],
    protonNmrChanges: ["O-H signal disappears or changes", "Aldehyde H near 9-10 ppm appears for aldehyde product"],
    carbonNmrChanges: ["New carbonyl carbon appears downfield"],
    massSpecChanges: ["Molecular ion mass changes as oxygen content changes"],
    explanation: "Oxidizing a primary alcohol replaces the alcohol signature with carbonyl evidence.",
  },
  {
    reactionId: "rxn-organic-ethanal-oxidation",
    reactionName: "Aldehyde Oxidation",
    reactantClass: "Aldehyde",
    productClass: "Carboxylic Acid",
    irChanges: ["Aldehyde C-H bands disappear", "Very broad acid O-H appears", "C=O remains strong"],
    protonNmrChanges: ["Aldehyde proton near 10 ppm disappears", "Acid proton near 10-13 ppm appears"],
    carbonNmrChanges: ["Carbonyl carbon shifts into the acid/ester region"],
    massSpecChanges: ["Molecular ion increases with added oxygen"],
    explanation: "Aldehyde to acid conversion is often recognized by loss of aldehydic H and appearance of acid O-H.",
  },
  {
    reactionId: "rxn-organic-ethanol-ethanoic-acid",
    reactionName: "Esterification",
    reactantClass: "Alcohol + Carboxylic Acid",
    productClass: "Ester",
    irChanges: ["Broad acid O-H disappears", "Ester C=O remains strong around 1735-1750 cm^-1", "C-O stretches remain in the fingerprint region"],
    protonNmrChanges: ["O-CH2 signal near 4 ppm may appear for ethyl esters", "Acid proton disappears"],
    carbonNmrChanges: ["Ester carbonyl carbon appears around 165-175 ppm"],
    massSpecChanges: ["Molecular ion reflects condensation product after loss of water"],
    explanation: "Esterification replaces acid/alcohol proton clues with ester carbonyl and alkoxy clues.",
  },
  {
    reactionId: "rxn-organic-propene-hydration",
    reactionName: "Alkene Hydration",
    reactantClass: "Alkene",
    productClass: "Alcohol",
    irChanges: ["C=C evidence decreases", "Broad alcohol O-H appears", "C-O stretch appears"],
    protonNmrChanges: ["Vinylic H signals disappear", "C-H near oxygen appears around 3-4 ppm"],
    carbonNmrChanges: ["sp2 alkene carbons are replaced by C-O and alkyl carbon signals"],
    massSpecChanges: ["Molecular ion increases by addition of H2O"],
    explanation: "Hydration converts alkene evidence into alcohol spectroscopy evidence.",
  },
  {
    reactionId: "rxn-organic-ethene-bromine",
    reactionName: "Alkene Bromination",
    reactantClass: "Alkene",
    productClass: "Dibromoalkane",
    irChanges: ["C=C stretch disappears", "Alkyl C-H remains"],
    protonNmrChanges: ["Vinylic H signals disappear", "Protons next to bromine shift downfield"],
    carbonNmrChanges: ["sp2 carbon signals disappear", "C-Br attached carbons appear in the alkyl region"],
    massSpecChanges: ["Bromine isotope pattern can appear with M and M+2 peaks"],
    explanation: "Bromination removes alkene pi-bond evidence and may introduce a bromine isotope pattern.",
  },
]
