import type { CompoundRecord } from "../../types"

type Seed = Omit<CompoundRecord, "kind" | "examBoards" | "topics" | "subtopics" | "tags"> &
  Partial<Pick<CompoundRecord, "topics" | "subtopics" | "tags">>

const boards = ["high-school", "ib-sl", "ib-hl", "ap", "a-level", "university-intro"] as const

function seed(s: Seed): CompoundRecord {
  return {
    kind: "compound",
    examBoards: [...boards],
    topics: s.topics ?? ["inorganic-chemistry"],
    subtopics: s.subtopics ?? [],
    tags: s.tags ?? [s.family],
    ...s,
  }
}

export const INORGANIC_COMPOUND_SEEDS: CompoundRecord[] = [
  seed({
    id: "compound-water",
    name: "water",
    aliases: ["water", "H2O", "dihydrogen monoxide"],
    formula: "H2O",
    condensed: "H—O—H",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Bent molecule with two O—H bonds; extensive hydrogen bonding.",
    structureArt: "    H\n     \\\n      O\n     /\n    H",
    commonReactions: ["Autoionization", "Hydrolysis", "Hydration"],
    lewisId: "lewis-h2o",
    vseprId: "vsepr-h2o",
    molecule3dId: "water",
    spectroscopyId: "spec-water",
    tags: ["inorganic", "vsepr-bent", "hydrogen-bonding"],
  }),
  seed({
    id: "compound-ammonia",
    name: "ammonia",
    aliases: ["ammonia", "NH3"],
    formula: "NH3",
    condensed: "NH3",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Trigonal pyramidal molecule with lone pair on nitrogen.",
    structureArt: "    H\n     \\\nH—N—H",
    commonReactions: ["Acid-base", "Complex formation"],
    lewisId: "lewis-nh3",
    vseprId: "vsepr-nh3",
    molecule3dId: "ammonia",
    tags: ["inorganic", "vsepr-trigonal-pyramidal"],
  }),
  seed({
    id: "compound-carbon-dioxide",
    name: "carbon dioxide",
    aliases: ["carbon dioxide", "CO2", "CO₂"],
    formula: "CO2",
    condensed: "O=C=O",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Nonpolar",
    hydrogenBonding: false,
    explanation: "Linear molecule; two C=O double bonds.",
    structureArt: "O=C=O",
    commonReactions: ["Photosynthesis reverse", "Acidic oxide"],
    lewisId: "lewis-co2",
    vseprId: "vsepr-co2",
    molecule3dId: "co2",
    tags: ["inorganic", "vsepr-linear"],
  }),
  seed({
    id: "compound-carbon-monoxide",
    name: "carbon monoxide",
    aliases: ["carbon monoxide", "CO"],
    formula: "CO",
    condensed: "C≡O",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Linear molecule with triple bond (resonance).",
    structureArt: ":C≡O:",
    commonReactions: ["Reducing agent", "Toxic binding to hemoglobin"],
    lewisId: "lewis-co",
    vseprId: "vsepr-co",
    tags: ["inorganic", "vsepr-linear"],
  }),
  seed({
    id: "compound-sulfur-dioxide",
    name: "sulfur dioxide",
    aliases: ["sulfur dioxide", "SO2", "SO₂"],
    formula: "SO2",
    condensed: "O=S=O",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Bent molecule with lone pair on sulfur.",
    structureArt: "O=S=O",
    commonReactions: ["Acid rain precursor", "Oxidation to SO3"],
    lewisId: "lewis-so2",
    vseprId: "vsepr-so2",
    tags: ["inorganic", "vsepr-bent"],
  }),
  seed({
    id: "compound-sulfur-trioxide",
    name: "sulfur trioxide",
    aliases: ["sulfur trioxide", "SO3", "SO₃"],
    formula: "SO3",
    condensed: "SO3",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Trigonal planar in gas phase.",
    structureArt: "  O\n  ║\nO—S—O",
    commonReactions: ["Forms H2SO4 with water"],
    lewisId: "lewis-so3",
    vseprId: "vsepr-so3",
    tags: ["inorganic", "vsepr-trigonal-planar"],
  }),
  seed({
    id: "compound-nitric-oxide",
    name: "nitric oxide",
    aliases: ["nitric oxide", "NO", "nitrogen monoxide"],
    formula: "NO",
    condensed: "N=O",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Radical with odd electron count.",
    structureArt: "·N=O",
    commonReactions: ["Atmospheric chemistry"],
    lewisId: "lewis-no",
    tags: ["inorganic", "radical"],
  }),
  seed({
    id: "compound-nitrogen-dioxide",
    name: "nitrogen dioxide",
    aliases: ["nitrogen dioxide", "NO2", "NO₂"],
    formula: "NO2",
    condensed: "NO2",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Bent radical molecule.",
    structureArt: "O=N—O",
    commonReactions: ["Acid rain", "Dimerization to N2O4"],
    lewisId: "lewis-no2",
    vseprId: "vsepr-no2",
    tags: ["inorganic", "vsepr-bent", "radical"],
  }),
  seed({
    id: "compound-dinitrogen-oxide",
    name: "dinitrogen oxide",
    aliases: ["dinitrogen oxide", "N2O", "nitrous oxide", "laughing gas"],
    formula: "N2O",
    condensed: "N=N=O",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Linear molecule with resonance.",
    structureArt: "N≡N→O",
    commonReactions: ["Anesthetic", "Greenhouse gas"],
    lewisId: "lewis-n2o",
    tags: ["inorganic", "vsepr-linear"],
  }),
  seed({
    id: "compound-ozone",
    name: "ozone",
    aliases: ["ozone", "O3", "O₃"],
    formula: "O3",
    condensed: "O3",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Bent molecule with resonance.",
    structureArt: "  O\n  ║\nO—O",
    commonReactions: ["Oxidizing agent", "UV absorption in stratosphere"],
    lewisId: "lewis-o3",
    vseprId: "vsepr-o3",
    tags: ["inorganic", "vsepr-bent", "resonance"],
  }),
  seed({
    id: "compound-hydrogen-chloride",
    name: "hydrogen chloride",
    aliases: ["hydrogen chloride", "HCl", "hydrochloric acid (aqueous)"],
    formula: "HCl",
    condensed: "H—Cl",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Polar diatomic; strong acid in water.",
    structureArt: "H—Cl",
    commonReactions: ["Acid-base", "Metal displacement"],
    lewisId: "lewis-hcl",
    vseprId: "vsepr-hcl",
    tags: ["inorganic", "vsepr-linear"],
  }),
  seed({
    id: "compound-hydrogen-fluoride",
    name: "hydrogen fluoride",
    aliases: ["hydrogen fluoride", "HF"],
    formula: "HF",
    condensed: "H—F",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Weak acid; strong hydrogen bonding.",
    structureArt: "H—F",
    commonReactions: ["Etching glass", "Acid-base"],
    tags: ["inorganic", "vsepr-linear"],
  }),
  seed({
    id: "compound-boron-trifluoride",
    name: "boron trifluoride",
    aliases: ["boron trifluoride", "BF3"],
    formula: "BF3",
    condensed: "BF3",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Trigonal planar; incomplete octet on boron.",
    structureArt: "  F\n  ║\nF—B—F",
    commonReactions: ["Lewis acid catalyst"],
    lewisId: "lewis-bf3",
    vseprId: "vsepr-bf3",
    tags: ["inorganic", "vsepr-trigonal-planar", "incomplete-octet"],
  }),
  seed({
    id: "compound-phosphorus-pentachloride",
    name: "phosphorus pentachloride",
    aliases: ["phosphorus pentachloride", "PCl5"],
    formula: "PCl5",
    condensed: "PCl5",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Trigonal bipyramidal; expanded octet.",
    structureArt: "PCl5 (TBP)",
    commonReactions: ["Chlorinating agent"],
    lewisId: "lewis-pcl5",
    vseprId: "vsepr-pcl5",
    tags: ["inorganic", "vsepr-trigonal-bipyramidal", "hypervalent"],
  }),
  seed({
    id: "compound-sulfur-hexafluoride",
    name: "sulfur hexafluoride",
    aliases: ["sulfur hexafluoride", "SF6"],
    formula: "SF6",
    condensed: "SF6",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Nonpolar",
    hydrogenBonding: false,
    explanation: "Octahedral; expanded octet on sulfur.",
    structureArt: "SF6 (Oh)",
    commonReactions: ["Electrical insulator"],
    lewisId: "lewis-sf6",
    vseprId: "vsepr-sf6",
    tags: ["inorganic", "vsepr-octahedral", "hypervalent"],
  }),
  seed({
    id: "compound-sulfur-tetrafluoride",
    name: "sulfur tetrafluoride",
    aliases: ["sulfur tetrafluoride", "SF4"],
    formula: "SF4",
    condensed: "SF4",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "See-saw molecular geometry.",
    structureArt: "SF4 (see-saw)",
    lewisId: "lewis-sf4",
    vseprId: "vsepr-sf4",
    tags: ["inorganic", "vsepr-see-saw", "hypervalent"],
  }),
  seed({
    id: "compound-xenon-tetrafluoride",
    name: "xenon tetrafluoride",
    aliases: ["xenon tetrafluoride", "XeF4"],
    formula: "XeF4",
    condensed: "XeF4",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Square planar molecular geometry.",
    structureArt: "XeF4 (square planar)",
    lewisId: "lewis-xef4",
    vseprId: "vsepr-xef4",
    tags: ["inorganic", "vsepr-square-planar", "hypervalent"],
  }),
  seed({
    id: "compound-chlorine-trifluoride",
    name: "chlorine trifluoride",
    aliases: ["chlorine trifluoride", "ClF3"],
    formula: "ClF3",
    condensed: "ClF3",
    family: "Inorganic",
    functionalGroup: "None",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "T-shaped molecular geometry.",
    structureArt: "ClF3 (T-shaped)",
    lewisId: "lewis-clf3",
    vseprId: "vsepr-clf3",
    tags: ["inorganic", "vsepr-t-shaped", "hypervalent"],
  }),
]
