import type { CompoundRecord } from "../../types"

const boards = ["ib-sl", "ib-hl", "ap", "a-level"] as const

function seed(
  s: Omit<CompoundRecord, "kind" | "examBoards" | "topics" | "subtopics" | "tags"> &
    Partial<Pick<CompoundRecord, "topics" | "subtopics" | "tags">>,
): CompoundRecord {
  return {
    kind: "compound",
    examBoards: [...boards, "high-school", "university-intro"],
    topics: s.topics ?? ["organic-chemistry"],
    subtopics: s.subtopics ?? [],
    tags: s.tags ?? [s.family],
    ...s,
  }
}

/** Named specialty compounds — complements generators */
export const SPECIALTY_ORGANIC_SEEDS: CompoundRecord[] = [
  seed({
    id: "compound-ethanol",
    name: "ethanol",
    aliases: ["ethanol", "ethyl alcohol", "C2H5OH", "C2H6O", "CH3CH2OH"],
    formula: "C2H6O",
    condensed: "CH3—CH2—OH",
    family: "Alcohol",
    functionalGroup: "Hydroxyl",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Two-carbon alcohol; common solvent and biofuel.",
    structureArt: "CH3—CH2—OH",
    commonReactions: ["Combustion", "Oxidation to ethanal", "Esterification"],
    molecule3dId: "ethanol",
    spectroscopyId: "spec-ethanol",
    subtopics: ["alcohols"],
  }),
  seed({
    id: "compound-propan-2-ol",
    name: "propan-2-ol",
    aliases: ["propan-2-ol", "isopropanol", "isopropyl alcohol", "rubbing alcohol"],
    formula: "C3H8O",
    condensed: "CH3—CH(OH)—CH3",
    family: "Alcohol",
    functionalGroup: "Hydroxyl",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Secondary alcohol.",
    structureArt: "CH3—CH(OH)—CH3",
    commonReactions: ["Oxidation to propanone", "Combustion"],
    molecule3dId: "propan-2-ol",
    subtopics: ["alcohols"],
  }),
  seed({
    id: "compound-propanone",
    name: "propanone",
    aliases: ["propanone", "acetone", "CH3COCH3"],
    formula: "C3H6O",
    condensed: "CH3—CO—CH3",
    family: "Ketone",
    functionalGroup: "Carbonyl",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Simplest ketone; common solvent.",
    structureArt: "CH3—CO—CH3",
    commonReactions: ["Nucleophilic addition", "Combustion"],
    spectroscopyId: "spec-propanone",
    subtopics: ["ketones"],
  }),
  seed({
    id: "compound-ethanoic-acid",
    name: "ethanoic acid",
    aliases: ["ethanoic acid", "acetic acid", "CH3COOH"],
    formula: "C2H4O2",
    condensed: "CH3—COOH",
    family: "Carboxylic acid",
    functionalGroup: "Carboxyl",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Weak acid in vinegar.",
    structureArt: "CH3—COOH",
    commonReactions: ["Esterification", "Neutralization"],
    molecule3dId: "ethanoic-acid",
    spectroscopyId: "spec-ethanoic-acid",
    subtopics: ["carboxylic-acids"],
  }),
  seed({
    id: "compound-methyl-ethanoate",
    name: "methyl ethanoate",
    aliases: ["methyl ethanoate", "methyl acetate", "CH3COOCH3"],
    formula: "C3H6O2",
    condensed: "CH3—COO—CH3",
    family: "Ester",
    functionalGroup: "Ester",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Fruity-smelling ester.",
    structureArt: "CH3—COO—CH3",
    commonReactions: ["Hydrolysis", "Saponification reverse"],
    spectroscopyId: "spec-methyl-ethanoate",
    subtopics: ["esters"],
  }),
  seed({
    id: "compound-phenol",
    name: "phenol",
    aliases: ["phenol", "C6H5OH", "carbolic acid"],
    formula: "C6H6O",
    condensed: "C6H5—OH",
    family: "Phenol",
    functionalGroup: "Phenyl + hydroxyl",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Weakly acidic aromatic alcohol.",
    structureArt: "C6H5—OH",
    commonReactions: ["Esterification", "Electrophilic substitution"],
    subtopics: ["phenols", "aromatics"],
  }),
  seed({
    id: "compound-aniline",
    name: "aniline",
    aliases: ["aniline", "phenylamine", "C6H5NH2"],
    formula: "C6H7N",
    condensed: "C6H5—NH2",
    family: "Amine",
    functionalGroup: "Amino (aromatic)",
    polarity: "Polar",
    hydrogenBonding: true,
    explanation: "Primary aromatic amine.",
    structureArt: "C6H5—NH2",
    commonReactions: ["Diazonium formation", "Acylation"],
    subtopics: ["amines"],
  }),
  seed({
    id: "compound-chloromethane",
    name: "chloromethane",
    aliases: ["chloromethane", "methyl chloride", "CH3Cl"],
    formula: "CH3Cl",
    condensed: "CH3—Cl",
    family: "Halogenoalkane",
    functionalGroup: "Halogeno",
    polarity: "Polar",
    hydrogenBonding: false,
    explanation: "Simple halogenoalkane.",
    structureArt: "CH3—Cl",
    commonReactions: ["SN2 substitution", "Elimination"],
    spectroscopyId: "spec-chloromethane",
    subtopics: ["halogenoalkanes"],
  }),
]
