import type { LewisStructure, LewisTemplate } from "./types"

function structure(partial: LewisStructure): LewisStructure {
  return partial
}

const templates: LewisTemplate[] = [
  {
    id: "lewis-h2o",
    formula: "H2O",
    name: "water",
    aliases: ["water", "H2O"],
    build: () =>
      structure({
        id: "lewis-h2o",
        formula: "H2O",
        name: "water",
        atoms: [
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
          { symbol: "H", valenceElectrons: 1, formalCharge: 0, lonePairs: 0, bondingElectrons: 2 },
          { symbol: "H", valenceElectrons: 1, formalCharge: 0, lonePairs: 0, bondingElectrons: 2 },
        ],
        bonds: [
          { from: 0, to: 1, order: 1 },
          { from: 0, to: 2, order: 1 },
        ],
        totalElectrons: 8,
        octetAnalysis: "O has full octet (2 lone pairs + 2 bonds); H has duet.",
        formalChargeSum: 0,
        hasResonance: false,
        isRadical: false,
        isHypervalent: false,
        bondOrders: "2 × O—H single bonds",
        lonePairSummary: "2 lone pairs on oxygen",
      }),
  },
  {
    id: "lewis-co2",
    formula: "CO2",
    name: "carbon dioxide",
    aliases: ["CO2", "carbon dioxide"],
    build: () =>
      structure({
        id: "lewis-co2",
        formula: "CO2",
        name: "carbon dioxide",
        atoms: [
          { symbol: "C", valenceElectrons: 4, formalCharge: 0, lonePairs: 0, bondingElectrons: 8 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
        ],
        bonds: [
          { from: 0, to: 1, order: 2 },
          { from: 0, to: 2, order: 2 },
        ],
        totalElectrons: 16,
        octetAnalysis: "All atoms achieve octet via double bonds.",
        formalChargeSum: 0,
        hasResonance: true,
        resonanceNote: "Two equivalent resonance forms O=C=O ↔ O⁻—C≡O⁺",
        isRadical: false,
        isHypervalent: false,
        bondOrders: "2 × C=O double bonds",
        lonePairSummary: "2 lone pairs on each oxygen",
      }),
  },
  {
    id: "lewis-no2",
    formula: "NO2",
    name: "nitrogen dioxide",
    aliases: ["NO2", "nitrogen dioxide"],
    build: () =>
      structure({
        id: "lewis-no2",
        formula: "NO2",
        name: "nitrogen dioxide",
        atoms: [
          { symbol: "N", valenceElectrons: 5, formalCharge: 0, lonePairs: 1, bondingElectrons: 6, incompleteOctet: false },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
        ],
        bonds: [
          { from: 0, to: 1, order: 1 },
          { from: 0, to: 2, order: 2 },
        ],
        totalElectrons: 17,
        octetAnalysis: "Odd electron count — radical. Resonance between N=O forms.",
        formalChargeSum: 0,
        hasResonance: true,
        resonanceNote: "Resonance stabilizes the unpaired electron.",
        isRadical: true,
        isHypervalent: false,
        bondOrders: "N=O and N—O (resonance)",
        lonePairSummary: "1 lone pair on N; lone pairs on O",
      }),
  },
  {
    id: "lewis-co3-2",
    formula: "CO3^2-",
    name: "carbonate",
    aliases: ["CO3^2-", "CO32-", "carbonate"],
    build: () =>
      structure({
        id: "lewis-co3-2",
        formula: "CO3^2-",
        name: "carbonate ion",
        atoms: [
          { symbol: "C", valenceElectrons: 4, formalCharge: 0, lonePairs: 0, bondingElectrons: 8 },
          { symbol: "O", valenceElectrons: 6, formalCharge: -1, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
          { symbol: "O", valenceElectrons: 6, formalCharge: -1, lonePairs: 3, bondingElectrons: 2 },
        ],
        bonds: [
          { from: 0, to: 1, order: 1 },
          { from: 0, to: 2, order: 2 },
          { from: 0, to: 3, order: 1 },
        ],
        totalElectrons: 24,
        octetAnalysis: "Three resonance structures; each C—O bond order ≈ 1.33.",
        formalChargeSum: -2,
        hasResonance: true,
        resonanceNote: "Three equivalent resonance contributors.",
        isRadical: false,
        isHypervalent: false,
        bondOrders: "Resonance-averaged C—O",
        lonePairSummary: "Lone pairs on each oxygen",
      }),
  },
  {
    id: "lewis-no3-minus",
    formula: "NO3-",
    name: "nitrate",
    aliases: ["NO3-", "nitrate"],
    build: () =>
      structure({
        id: "lewis-no3-minus",
        formula: "NO3-",
        name: "nitrate ion",
        atoms: [
          { symbol: "N", valenceElectrons: 5, formalCharge: 0, lonePairs: 0, bondingElectrons: 8 },
          { symbol: "O", valenceElectrons: 6, formalCharge: -1, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
          { symbol: "O", valenceElectrons: 6, formalCharge: -1, lonePairs: 3, bondingElectrons: 2 },
        ],
        bonds: [
          { from: 0, to: 1, order: 1 },
          { from: 0, to: 2, order: 2 },
          { from: 0, to: 3, order: 1 },
        ],
        totalElectrons: 24,
        octetAnalysis: "N central atom with three resonance forms.",
        formalChargeSum: -1,
        hasResonance: true,
        resonanceNote: "Delocalized π system over N and three O atoms.",
        isRadical: false,
        isHypervalent: false,
        bondOrders: "Resonance-averaged N—O",
        lonePairSummary: "Lone pairs on oxygens",
      }),
  },
  {
    id: "lewis-o3",
    formula: "O3",
    name: "ozone",
    aliases: ["O3", "ozone"],
    build: () =>
      structure({
        id: "lewis-o3",
        formula: "O3",
        name: "ozone",
        atoms: [
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 1, bondingElectrons: 6 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
        ],
        bonds: [
          { from: 0, to: 1, order: 2 },
          { from: 1, to: 2, order: 1 },
        ],
        totalElectrons: 18,
        octetAnalysis: "Central O has expanded bonding; two resonance forms.",
        formalChargeSum: 0,
        hasResonance: true,
        resonanceNote: "Resonance between terminal O positions.",
        isRadical: false,
        isHypervalent: false,
        bondOrders: "O=O—O ↔ O—O=O",
        lonePairSummary: "Lone pairs on terminal and central O",
      }),
  },
  {
    id: "lewis-so4-2",
    formula: "SO4^2-",
    name: "sulfate",
    aliases: ["SO4^2-", "SO42-", "sulfate"],
    build: () =>
      structure({
        id: "lewis-so4-2",
        formula: "SO4^2-",
        name: "sulfate ion",
        atoms: [
          { symbol: "S", valenceElectrons: 6, formalCharge: 0, lonePairs: 0, bondingElectrons: 8, expandedOctet: true },
          { symbol: "O", valenceElectrons: 6, formalCharge: -1, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "O", valenceElectrons: 6, formalCharge: -1, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
          { symbol: "O", valenceElectrons: 6, formalCharge: 0, lonePairs: 2, bondingElectrons: 4 },
        ],
        bonds: [
          { from: 0, to: 1, order: 1 },
          { from: 0, to: 2, order: 1 },
          { from: 0, to: 3, order: 2 },
          { from: 0, to: 4, order: 2 },
        ],
        totalElectrons: 32,
        octetAnalysis: "S expands octet (12 electrons) — hypervalent.",
        formalChargeSum: -2,
        hasResonance: true,
        resonanceNote: "Six equivalent resonance structures.",
        isRadical: false,
        isHypervalent: true,
        bondOrders: "S=O and S—O (resonance)",
        lonePairSummary: "Lone pairs on each oxygen",
      }),
  },
  {
    id: "lewis-bf3",
    formula: "BF3",
    name: "boron trifluoride",
    aliases: ["BF3", "boron trifluoride"],
    build: () =>
      structure({
        id: "lewis-bf3",
        formula: "BF3",
        name: "boron trifluoride",
        atoms: [
          { symbol: "B", valenceElectrons: 3, formalCharge: 0, lonePairs: 0, bondingElectrons: 6, incompleteOctet: true },
          { symbol: "F", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "F", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "F", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
        ],
        bonds: [
          { from: 0, to: 1, order: 1 },
          { from: 0, to: 2, order: 1 },
          { from: 0, to: 3, order: 1 },
        ],
        totalElectrons: 24,
        octetAnalysis: "B has only 6 valence electrons — incomplete octet. Lewis acid.",
        formalChargeSum: 0,
        hasResonance: false,
        isRadical: false,
        isHypervalent: false,
        bondOrders: "3 × B—F single bonds",
        lonePairSummary: "3 lone pairs on each F",
      }),
  },
  {
    id: "lewis-cn-minus",
    formula: "CN-",
    name: "cyanide",
    aliases: ["CN-", "cyanide"],
    build: () =>
      structure({
        id: "lewis-cn-minus",
        formula: "CN-",
        name: "cyanide ion",
        atoms: [
          { symbol: "C", valenceElectrons: 4, formalCharge: -1, lonePairs: 1, bondingElectrons: 6 },
          { symbol: "N", valenceElectrons: 5, formalCharge: 0, lonePairs: 1, bondingElectrons: 6 },
        ],
        bonds: [{ from: 0, to: 1, order: 3 }],
        totalElectrons: 10,
        octetAnalysis: "Triple bond gives both atoms octet.",
        formalChargeSum: -1,
        hasResonance: true,
        resonanceNote: ":C≡N: ↔ :C⁻=N: (minor contributor)",
        isRadical: false,
        isHypervalent: false,
        bondOrders: "C≡N triple bond",
        lonePairSummary: "1 lone pair on each atom in major form",
      }),
  },
  {
    id: "lewis-pcl5",
    formula: "PCl5",
    name: "phosphorus pentachloride",
    aliases: ["PCl5"],
    build: () =>
      structure({
        id: "lewis-pcl5",
        formula: "PCl5",
        name: "phosphorus pentachloride",
        atoms: [
          { symbol: "P", valenceElectrons: 5, formalCharge: 0, lonePairs: 0, bondingElectrons: 10, expandedOctet: true },
          { symbol: "Cl", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "Cl", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "Cl", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "Cl", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
          { symbol: "Cl", valenceElectrons: 7, formalCharge: 0, lonePairs: 3, bondingElectrons: 2 },
        ],
        bonds: [1, 2, 3, 4, 5].map((i) => ({ from: 0, to: i, order: 1 as const })),
        totalElectrons: 40,
        octetAnalysis: "P has 10 valence electrons — expanded octet.",
        formalChargeSum: 0,
        hasResonance: false,
        isRadical: false,
        isHypervalent: true,
        bondOrders: "5 × P—Cl single bonds",
        lonePairSummary: "3 lone pairs on each Cl",
      }),
  },
]

export const LEWIS_TEMPLATES: LewisTemplate[] = templates

export const ALL_LEWIS_STRUCTURES: LewisStructure[] = templates.map((t) => t.build())
