import type { HybridizationPreset } from "./hybridization-types"

export const HYBRIDIZATION_PRESETS: HybridizationPreset[] = [
  {
    id: "becl2",
    label: "BeCl2",
    formula: "BeCl2",
    centralAtom: "Be",
    outerAtoms: ["Cl", "Cl"],
    mode: "sp",
    electronDomains: 2,
    bondingDomains: 2,
    lonePairs: 0,
    electronGeometry: "Linear",
    molecularGeometry: "Linear",
    idealBondAngles: "180 deg",
    explanation: "Beryllium has two bonding domains, so the electron domains point opposite each other.",
  },
  {
    id: "bf3",
    label: "BF3",
    formula: "BF3",
    centralAtom: "B",
    outerAtoms: ["F", "F", "F"],
    mode: "sp2",
    electronDomains: 3,
    bondingDomains: 3,
    lonePairs: 0,
    electronGeometry: "Trigonal planar",
    molecularGeometry: "Trigonal planar",
    idealBondAngles: "120 deg",
    explanation: "Boron has three bonding domains arranged in one plane.",
  },
  {
    id: "ch4",
    label: "CH4",
    formula: "CH4",
    centralAtom: "C",
    outerAtoms: ["H", "H", "H", "H"],
    mode: "sp3",
    electronDomains: 4,
    bondingDomains: 4,
    lonePairs: 0,
    electronGeometry: "Tetrahedral",
    molecularGeometry: "Tetrahedral",
    idealBondAngles: "109.5 deg",
    explanation: "Methane uses four equivalent sp3 directions for sigma bonds to hydrogen.",
  },
  {
    id: "nh3",
    label: "NH3",
    formula: "NH3",
    centralAtom: "N",
    outerAtoms: ["H", "H", "H"],
    mode: "sp3",
    electronDomains: 4,
    bondingDomains: 3,
    lonePairs: 1,
    electronGeometry: "Tetrahedral",
    molecularGeometry: "Trigonal pyramidal",
    idealBondAngles: "about 107 deg",
    explanation:
      "Ammonia has four electron domains, but one is a lone pair, so the molecular geometry is trigonal pyramidal.",
  },
  {
    id: "h2o",
    label: "H2O",
    formula: "H2O",
    centralAtom: "O",
    outerAtoms: ["H", "H"],
    mode: "sp3",
    electronDomains: 4,
    bondingDomains: 2,
    lonePairs: 2,
    electronGeometry: "Tetrahedral",
    molecularGeometry: "Bent",
    idealBondAngles: "about 104.5 deg",
    explanation:
      "Water has two bonding domains and two lone pairs. Lone-pair repulsion gives a bent molecular shape.",
  },
  {
    id: "pcl5",
    label: "PCl5",
    formula: "PCl5",
    centralAtom: "P",
    outerAtoms: ["Cl", "Cl", "Cl", "Cl", "Cl"],
    mode: "sp3d",
    electronDomains: 5,
    bondingDomains: 5,
    lonePairs: 0,
    electronGeometry: "Trigonal bipyramidal",
    molecularGeometry: "Trigonal bipyramidal",
    idealBondAngles: "90 deg, 120 deg, 180 deg",
    explanation: "Five bonding domains arrange into three equatorial and two axial directions.",
  },
  {
    id: "sf6",
    label: "SF6",
    formula: "SF6",
    centralAtom: "S",
    outerAtoms: ["F", "F", "F", "F", "F", "F"],
    mode: "sp3d2",
    electronDomains: 6,
    bondingDomains: 6,
    lonePairs: 0,
    electronGeometry: "Octahedral",
    molecularGeometry: "Octahedral",
    idealBondAngles: "90 deg, 180 deg",
    explanation: "Six bonding domains point toward an octahedron.",
  },
  {
    id: "xef4",
    label: "XeF4",
    formula: "XeF4",
    centralAtom: "Xe",
    outerAtoms: ["F", "F", "F", "F"],
    mode: "sp3d2",
    electronDomains: 6,
    bondingDomains: 4,
    lonePairs: 2,
    electronGeometry: "Octahedral",
    molecularGeometry: "Square planar",
    idealBondAngles: "90 deg, 180 deg",
    explanation:
      "Xenon tetrafluoride has six electron domains. Two opposite lone pairs leave four F atoms in a square plane.",
  },
]

const presetById = new Map(HYBRIDIZATION_PRESETS.map((preset) => [preset.id, preset]))

export function listHybridizationPresets(): HybridizationPreset[] {
  return HYBRIDIZATION_PRESETS
}

export function getHybridizationPreset(id: string): HybridizationPreset | undefined {
  return presetById.get(id)
}
