import { REACTION_RECORDS } from "../chemistry/reactions"
import type { ReactionRecord } from "../chemistry/reaction-types"
import type { ReactionConditionMetrics, ReactionConditionRecord } from "./reaction-condition-types"

function condition(input: ReactionConditionRecord): ReactionConditionRecord {
  return input
}

export const REACTION_CONDITION_RECORDS: ReactionConditionRecord[] = [
  condition({
    reactionId: "rxn-organic-ethanol-oxidation",
    reactionName: "Alcohol Oxidation",
    reagents: ["K2Cr2O7", "H2SO4"],
    catalysts: ["H2SO4"],
    solvents: ["aqueous acid"],
    temperature: "Heat gently for aldehyde; reflux for carboxylic acid",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Moderate to good; aldehyde yield depends on distillation",
    commonSideReactions: ["Over-oxidation to carboxylic acid", "Incomplete oxidation if not heated enough"],
    commonMistakes: ["Forgetting acidified conditions", "Writing aldehyde as final product under reflux"],
    safetyNotes: ["Strong oxidizer", "Acidic dichromate is corrosive and toxic"],
    mechanismFamily: "Oxidation",
    difficulty: "Intermediate",
    expectedProducts: ["Ethanal", "Ethanoic acid"],
    typicalExamClues: ["orange dichromate turns green", "primary alcohol", "heat or reflux"],
  }),
  condition({
    reactionId: "rxn-organic-ethanal-oxidation",
    reactionName: "Aldehyde Oxidation",
    reagents: ["K2Cr2O7", "H2SO4"],
    catalysts: ["H2SO4"],
    solvents: ["aqueous acid"],
    temperature: "Heat under reflux",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good",
    commonSideReactions: ["Further side reactions if impure sample is overheated"],
    commonMistakes: ["Confusing aldehyde oxidation with ketone oxidation"],
    safetyNotes: ["Strong oxidizer", "Corrosive acid"],
    mechanismFamily: "Oxidation",
    difficulty: "Intermediate",
    expectedProducts: ["Ethanoic acid"],
    typicalExamClues: ["aldehyde", "acidified dichromate", "carboxylic acid product"],
  }),
  condition({
    reactionId: "rxn-organic-ethene-bromine",
    reactionName: "Alkene Bromination",
    reagents: ["Br2"],
    catalysts: [],
    solvents: ["non-polar solvent or aqueous bromine for testing"],
    temperature: "Room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good for simple alkenes",
    commonSideReactions: ["Bromohydrin formation in water"],
    commonMistakes: ["Using UV light as if it were alkane substitution", "Forgetting the bromine color test"],
    safetyNotes: ["Bromine is corrosive and volatile"],
    mechanismFamily: "Electrophilic addition",
    difficulty: "Introductory",
    expectedProducts: ["1,2-dibromoethane"],
    typicalExamClues: ["orange bromine decolorizes", "C=C double bond", "addition reaction"],
  }),
  condition({
    reactionId: "rxn-hydrocarbon-propene-bromine",
    reactionName: "Propene Bromination",
    reagents: ["Br2"],
    catalysts: [],
    solvents: ["non-polar solvent or aqueous bromine"],
    temperature: "Room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good",
    commonSideReactions: ["Bromohydrin formation in water"],
    commonMistakes: ["Applying substitution conditions instead of addition"],
    safetyNotes: ["Bromine is corrosive and volatile"],
    mechanismFamily: "Electrophilic addition",
    difficulty: "Introductory",
    expectedProducts: ["1,2-dibromopropane"],
    typicalExamClues: ["alkene", "bromine water", "decolorization"],
  }),
  condition({
    reactionId: "rxn-organic-ethene-hydrogen",
    reactionName: "Alkene Hydrogenation",
    reagents: ["H2"],
    catalysts: ["Ni", "Pt", "Pd"],
    solvents: ["none or inert solvent"],
    temperature: "Heat",
    pressure: "Elevated H2 pressure",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good",
    commonSideReactions: ["Over-reduction in more complex molecules"],
    commonMistakes: ["Forgetting the metal catalyst", "Calling it substitution"],
    safetyNotes: ["Hydrogen is flammable", "Use pressure apparatus carefully"],
    mechanismFamily: "Catalytic hydrogenation",
    difficulty: "Intermediate",
    expectedProducts: ["Ethane"],
    typicalExamClues: ["H2/Ni", "alkene to alkane", "saturation"],
  }),
  condition({
    reactionId: "rxn-hydrocarbon-ethyne-hydrogen",
    reactionName: "Alkyne Hydrogenation",
    reagents: ["H2"],
    catalysts: ["Ni", "Pt", "Pd"],
    solvents: ["inert solvent"],
    temperature: "Heat",
    pressure: "Elevated H2 pressure",
    reactionCategory: "Organic Reactions",
    typicalYield: "Moderate to good",
    commonSideReactions: ["Over-reduction to alkane"],
    commonMistakes: ["Not accounting for two pi bonds in alkynes"],
    safetyNotes: ["Hydrogen is flammable"],
    mechanismFamily: "Catalytic hydrogenation",
    difficulty: "Intermediate",
    expectedProducts: ["Ethane"],
    typicalExamClues: ["alkyne", "H2 with metal catalyst", "addition"],
  }),
  condition({
    reactionId: "rxn-organic-propene-hydration",
    reactionName: "Alkene Hydration",
    reagents: ["H2O", "H3O+"],
    catalysts: ["H2SO4 or H3PO4"],
    solvents: ["aqueous acid"],
    temperature: "Heat",
    pressure: "Elevated steam pressure for industrial hydration",
    reactionCategory: "Organic Reactions",
    typicalYield: "Moderate; equilibrium limited",
    commonSideReactions: ["Carbocation rearrangement for suitable substrates", "Polymerization under strong acid"],
    commonMistakes: ["Ignoring Markovnikov orientation", "Forgetting acid catalyst"],
    safetyNotes: ["Strong acids are corrosive", "Industrial process uses pressure"],
    mechanismFamily: "Electrophilic addition",
    difficulty: "Intermediate",
    expectedProducts: ["Propan-2-ol"],
    typicalExamClues: ["steam", "acid catalyst", "alkene to alcohol"],
  }),
  condition({
    reactionId: "rxn-organic-ethene-hbr",
    reactionName: "Hydrohalogenation",
    reagents: ["HBr"],
    catalysts: [],
    solvents: ["inert organic solvent"],
    temperature: "Room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good for simple alkenes",
    commonSideReactions: ["Regioisomer mixtures for unsymmetrical alkenes"],
    commonMistakes: ["Forgetting Markovnikov addition"],
    safetyNotes: ["Hydrogen bromide is corrosive"],
    mechanismFamily: "Electrophilic addition",
    difficulty: "Intermediate",
    expectedProducts: ["Bromoethane"],
    typicalExamClues: ["HBr", "alkene", "haloalkane product"],
  }),
  condition({
    reactionId: "rxn-organic-ethanol-ethanoic-acid",
    reactionName: "Esterification",
    reagents: ["ethanol", "ethanoic acid"],
    catalysts: ["concentrated H2SO4"],
    solvents: ["reactants often act as solvent"],
    temperature: "Heat under reflux",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Moderate because reaction is reversible",
    commonSideReactions: ["Hydrolysis if water is present", "Dehydration under very strong acid/heat"],
    commonMistakes: ["Forgetting water as byproduct", "Forgetting acid catalyst"],
    safetyNotes: ["Concentrated sulfuric acid is corrosive and dehydrating"],
    mechanismFamily: "Condensation",
    difficulty: "Intermediate",
    expectedProducts: ["Ethyl ethanoate", "Water"],
    typicalExamClues: ["fruity smell", "alcohol plus carboxylic acid", "concentrated H2SO4"],
  }),
  condition({
    reactionId: "rxn-organic-ester-hydrolysis",
    reactionName: "Ester Hydrolysis",
    reagents: ["H2O"],
    catalysts: ["dilute acid or NaOH"],
    solvents: ["aqueous acid/base"],
    temperature: "Heat under reflux",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good; base hydrolysis is effectively irreversible",
    commonSideReactions: ["Incomplete hydrolysis if reflux time is short"],
    commonMistakes: ["Missing carboxylate salt under basic conditions"],
    safetyNotes: ["Acids and bases are corrosive"],
    mechanismFamily: "Hydrolysis",
    difficulty: "Intermediate",
    expectedProducts: ["Carboxylic acid or carboxylate", "Alcohol"],
    typicalExamClues: ["ester plus water", "reflux", "acidic or alkaline hydrolysis"],
  }),
  condition({
    reactionId: "rxn-organic-bromoethane-oh",
    reactionName: "Haloalkane Hydrolysis",
    reagents: ["OH-"],
    catalysts: [],
    solvents: ["aqueous ethanol"],
    temperature: "Heat under reflux",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good for primary haloalkanes",
    commonSideReactions: ["Elimination to alkene with hot ethanolic base"],
    commonMistakes: ["Confusing aqueous and ethanolic hydroxide outcomes"],
    safetyNotes: ["Haloalkanes may be harmful", "Hot base is corrosive"],
    mechanismFamily: "Nucleophilic substitution",
    difficulty: "Intermediate",
    expectedProducts: ["Ethanol"],
    typicalExamClues: ["haloalkane", "aqueous hydroxide", "alcohol product"],
  }),
  condition({
    reactionId: "rxn-organic-benzene-nitration",
    reactionName: "Benzene Nitration",
    reagents: ["HNO3"],
    catalysts: ["H2SO4"],
    solvents: ["concentrated acid mixture"],
    temperature: "50-60 C",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Good when temperature is controlled",
    commonSideReactions: ["Multiple nitration if overheated"],
    commonMistakes: ["Using bromination conditions", "Forgetting sulfuric acid generates electrophile"],
    safetyNotes: ["Concentrated acids are corrosive", "Nitration mixtures require temperature control"],
    mechanismFamily: "Electrophilic aromatic substitution",
    difficulty: "Advanced",
    expectedProducts: ["Nitrobenzene"],
    typicalExamClues: ["benzene", "HNO3/H2SO4", "50-60 C"],
  }),
  condition({
    reactionId: "rxn-organic-alkane-chlorination",
    reactionName: "Alkane Chlorination",
    reagents: ["Cl2"],
    catalysts: ["UV light"],
    solvents: ["none or inert solvent"],
    temperature: "UV light at room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Mixture of products",
    commonSideReactions: ["Multiple substitution", "Isomer mixtures"],
    commonMistakes: ["Calling this alkene addition", "Forgetting UV light"],
    safetyNotes: ["Chlorine is toxic", "Radical chlorination is not selective"],
    mechanismFamily: "Free-radical substitution",
    difficulty: "Intermediate",
    expectedProducts: ["Chloromethane", "HCl"],
    typicalExamClues: ["alkane", "chlorine", "UV light"],
  }),
  condition({
    reactionId: "rxn-organic-dehydration-ethanol",
    reactionName: "Alcohol Dehydration",
    reagents: ["ethanol"],
    catalysts: ["concentrated H2SO4 or Al2O3"],
    solvents: ["none"],
    temperature: "Heat",
    pressure: "Atmospheric",
    reactionCategory: "Organic Reactions",
    typicalYield: "Moderate to good",
    commonSideReactions: ["Ether formation at lower temperatures"],
    commonMistakes: ["Confusing dehydration with oxidation"],
    safetyNotes: ["Concentrated acid is corrosive", "Ethene is flammable"],
    mechanismFamily: "Elimination",
    difficulty: "Intermediate",
    expectedProducts: ["Ethene", "Water"],
    typicalExamClues: ["remove water", "alcohol to alkene", "concentrated acid"],
  }),
  condition({
    reactionId: "rxn-neutralization-hcl-naoh",
    reactionName: "Neutralization",
    reagents: ["HCl", "NaOH"],
    catalysts: [],
    solvents: ["water"],
    temperature: "Room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Acid-Base",
    typicalYield: "Quantitative in aqueous solution",
    commonSideReactions: ["None significant for strong acid/strong base"],
    commonMistakes: ["Not balancing water formation", "Ignoring spectator ions in net ionic equations"],
    safetyNotes: ["Acids and bases are corrosive"],
    mechanismFamily: "Proton transfer",
    difficulty: "Introductory",
    expectedProducts: ["NaCl", "H2O"],
    typicalExamClues: ["acid plus base", "salt plus water", "neutralization"],
  }),
  condition({
    reactionId: "rxn-precip-agcl",
    reactionName: "Silver Chloride Precipitation",
    reagents: ["AgNO3", "NaCl"],
    catalysts: [],
    solvents: ["water"],
    temperature: "Room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Precipitation",
    typicalYield: "High if ions are mixed in excess",
    commonSideReactions: ["Silver halide photodecomposition under bright light"],
    commonMistakes: ["Choosing nitrate as precipitate", "Forgetting spectator ions remain aqueous"],
    safetyNotes: ["Silver nitrate stains skin and is an irritant"],
    mechanismFamily: "Ion exchange",
    difficulty: "Introductory",
    expectedProducts: ["AgCl(s)"],
    typicalExamClues: ["white precipitate", "Ag+ with Cl-", "halide test"],
  }),
  condition({
    reactionId: "rxn-combustion-methane",
    reactionName: "Methane Combustion",
    reagents: ["O2"],
    catalysts: ["spark or flame"],
    solvents: ["gas phase"],
    temperature: "Ignition temperature",
    pressure: "Atmospheric",
    reactionCategory: "Combustion",
    typicalYield: "Complete when oxygen is in excess",
    commonSideReactions: ["CO and soot formation with limited oxygen"],
    commonMistakes: ["Forgetting water product", "Not balancing O2"],
    safetyNotes: ["Flammable gas", "Combustion can be explosive in air mixtures"],
    mechanismFamily: "Combustion radical chain",
    difficulty: "Introductory",
    expectedProducts: ["CO2", "H2O"],
    typicalExamClues: ["hydrocarbon plus oxygen", "complete combustion", "CO2 and H2O"],
  }),
  condition({
    reactionId: "rxn-displacement-zn-cuso4",
    reactionName: "Zinc Displaces Copper",
    reagents: ["Zn", "CuSO4"],
    catalysts: [],
    solvents: ["water"],
    temperature: "Room temperature",
    pressure: "Atmospheric",
    reactionCategory: "Redox",
    typicalYield: "Good if zinc surface is clean",
    commonSideReactions: ["Oxide coating slows reaction"],
    commonMistakes: ["Reversing the activity series", "Forgetting sulfate is spectator"],
    safetyNotes: ["Copper sulfate is harmful if swallowed"],
    mechanismFamily: "Single displacement redox",
    difficulty: "Introductory",
    expectedProducts: ["ZnSO4", "Cu"],
    typicalExamClues: ["more reactive metal displaces less reactive metal", "blue solution fades"],
  }),
  condition({
    reactionId: "rxn-equilibrium-haber",
    reactionName: "Haber Equilibrium",
    reagents: ["N2", "H2"],
    catalysts: ["Fe"],
    solvents: ["gas phase"],
    temperature: "About 450 C",
    pressure: "High pressure, about 200 atm",
    reactionCategory: "Equilibrium",
    typicalYield: "Moderate per pass; improved by recycling gases",
    commonSideReactions: ["Minimal under industrial conditions"],
    commonMistakes: ["Assuming lower temperature is always industrially best", "Forgetting compromise conditions"],
    safetyNotes: ["High pressure industrial process", "Hydrogen is flammable"],
    mechanismFamily: "Heterogeneous catalysis",
    difficulty: "Advanced",
    expectedProducts: ["NH3"],
    typicalExamClues: ["iron catalyst", "high pressure", "ammonia synthesis"],
  }),
]

function fallbackFor(record: ReactionRecord): ReactionConditionRecord {
  const category = record.category
  const base = {
    reactionId: record.id,
    reactionName: record.name,
    reactionCategory: category,
    difficulty: record.difficulty,
    expectedProducts: record.products,
  }

  if (category === "Acid-Base") {
    return {
      ...base,
      reagents: record.reactants,
      catalysts: [],
      solvents: ["water"],
      temperature: "Room temperature",
      pressure: "Atmospheric",
      typicalYield: "Usually quantitative for strong acid/base systems",
      commonSideReactions: ["Usually minimal in classroom examples"],
      commonMistakes: ["Ignoring spectator ions", "Forgetting salt plus water products"],
      safetyNotes: ["Acids and bases may be corrosive"],
      mechanismFamily: "Proton transfer",
      typicalExamClues: ["acid plus base", "salt plus water", "pH change"],
    }
  }

  if (category === "Precipitation" || category === "Double Displacement") {
    return {
      ...base,
      reagents: record.reactants,
      catalysts: [],
      solvents: ["water"],
      temperature: "Room temperature",
      pressure: "Atmospheric",
      typicalYield: "High when an insoluble product forms",
      commonSideReactions: ["Competing precipitates if extra ions are present"],
      commonMistakes: ["Choosing a spectator ion as the precipitate"],
      safetyNotes: ["Use standard aqueous salt handling precautions"],
      mechanismFamily: "Ion exchange",
      typicalExamClues: ["aqueous salts", "solid precipitate", "solubility rules"],
    }
  }

  if (category === "Combustion") {
    return {
      ...base,
      reagents: ["O2"],
      catalysts: ["spark or flame"],
      solvents: ["gas phase"],
      temperature: "Ignition temperature",
      pressure: "Atmospheric",
      typicalYield: "Complete when oxygen is in excess",
      commonSideReactions: ["CO or carbon soot if oxygen is limited"],
      commonMistakes: ["Forgetting CO2 and H2O as complete-combustion products"],
      safetyNotes: ["Flammable reactants; avoid open flames outside controlled demonstrations"],
      mechanismFamily: "Combustion radical chain",
      typicalExamClues: ["fuel plus oxygen", "exothermic", "complete combustion"],
    }
  }

  if (category === "Redox" || category === "Single Displacement" || category === "Electrochemistry") {
    return {
      ...base,
      reagents: record.reactants,
      catalysts: [],
      solvents: ["water or indicated cell medium"],
      temperature: "Room temperature unless stated",
      pressure: "Atmospheric",
      typicalYield: "Depends on electrode/reactant purity",
      commonSideReactions: ["Surface oxide layers may slow metal reactions"],
      commonMistakes: ["Reversing oxidation and reduction", "Forgetting spectator ions"],
      safetyNotes: ["Follow handling notes for metal salts and oxidizers"],
      mechanismFamily: "Electron transfer",
      typicalExamClues: ["oxidation numbers change", "metal displacement", "cell potential"],
    }
  }

  if (category === "Equilibrium") {
    return {
      ...base,
      reagents: record.reactants,
      catalysts: [],
      solvents: ["gas phase or aqueous mixture as written"],
      temperature: "Controlled temperature",
      pressure: "Controlled pressure when gases are involved",
      typicalYield: "Equilibrium-limited",
      commonSideReactions: ["Depends on system impurities"],
      commonMistakes: ["Confusing rate with equilibrium position"],
      safetyNotes: ["Use process-specific safety data"],
      mechanismFamily: "Reversible equilibrium",
      typicalExamClues: ["reversible arrow", "K or Le Chatelier", "compromise conditions"],
    }
  }

  return {
    ...base,
    reagents: record.reactants,
    catalysts: [],
    solvents: ["as appropriate for the reaction"],
    temperature: "Room temperature unless stated",
    pressure: "Atmospheric unless stated",
    typicalYield: "Varies by substrate and conditions",
    commonSideReactions: ["Depends on reactant purity and reaction class"],
    commonMistakes: ["Memorizing products without checking the reaction family"],
    safetyNotes: ["Use standard laboratory PPE and verify chemical hazards"],
    mechanismFamily: record.reactionType,
    typicalExamClues: [record.reactionType, record.category],
  }
}

const CONDITIONS_BY_ID = new Map(REACTION_CONDITION_RECORDS.map((record) => [record.reactionId, record]))

export function getReactionConditions(reactionId: string | undefined): ReactionConditionRecord | undefined {
  if (!reactionId) return undefined
  const direct = CONDITIONS_BY_ID.get(reactionId)
  if (direct) return direct
  const reaction = REACTION_RECORDS.find((record) => record.id === reactionId)
  return reaction ? fallbackFor(reaction) : undefined
}

export function getReactionConditionsForRecord(record: ReactionRecord): ReactionConditionRecord {
  return getReactionConditions(record.id) ?? fallbackFor(record)
}

export function listReactionConditions(): ReactionConditionRecord[] {
  return REACTION_RECORDS.map(getReactionConditionsForRecord)
}

export function getReactionConditionForMechanism(mechanismId: string | undefined): ReactionConditionRecord | undefined {
  const mapping: Record<string, string> = {
    "alkene-bromination": "rxn-organic-ethene-bromine",
    "alkene-hydration": "rxn-organic-propene-hydration",
    "alkene-hydrogenation": "rxn-organic-ethene-hydrogen",
    esterification: "rxn-organic-ethanol-ethanoic-acid",
    "sn1-substitution": "rxn-organic-bromoethane-oh",
    "sn2-substitution": "rxn-organic-bromoethane-oh",
    "e1-elimination": "rxn-organic-dehydration-ethanol",
    "e2-elimination": "rxn-organic-dehydration-ethanol",
    "alcohol-oxidation": "rxn-organic-ethanol-oxidation",
    "carboxylic-acid-formation": "rxn-organic-ethanal-oxidation",
  }
  return getReactionConditions(mapping[mechanismId ?? ""])
}

export function getReactionConditionMetrics(): ReactionConditionMetrics {
  const conditions = listReactionConditions()
  return {
    records: conditions.length,
    mechanismFamilies: new Set(conditions.map((record) => record.mechanismFamily)).size,
    reagentSets: new Set(conditions.map((record) => record.reagents.join(" + "))).size,
    safetyNotes: conditions.reduce((sum, record) => sum + record.safetyNotes.length, 0),
  }
}
