import type { StructureScannerRecord } from "./scanner-types"

const ORGANIC_FORMULA = "organic-homologous-series"
const ORGANIC_UNSATURATION = "organic-degree-unsaturation"
const MOLARITY_FORMULA = "solutions-molarity"
const PH_FORMULA = "acids-bases-ph"
const STOICHIOMETRY_FORMULA = "stoichiometry-moles-from-mass"

export const STRUCTURE_SCANNER_RECORDS: StructureScannerRecord[] = [
  {
    id: "water",
    name: "Water",
    formula: "H2O",
    functionalGroups: ["oxide", "hydrogen bonding"],
    commonAliases: ["dihydrogen monoxide"],
    difficulty: "Introductory",
    reactionGraphLinks: ["acid-base pathway", "stoichiometry pathway"],
    visualizerLinks: ["water"],
    formulaId: MOLARITY_FORMULA,
    practiceTopic: "Bonding",
    examTopic: "Bonding",
    curriculumTopicId: "bonding",
    recommendedCurriculumTopics: [{ id: "bonding", label: "Bonding" }],
    keywords: ["bent", "polar", "hydrogen bonding"],
  },
  {
    id: "hydrogen-peroxide",
    name: "Hydrogen peroxide",
    formula: "H2O2",
    functionalGroups: ["peroxide"],
    commonAliases: ["peroxide"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["redox"],
    visualizerLinks: ["hydrogen-peroxide"],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Redox",
    examTopic: "Redox",
    curriculumTopicId: "electrochemistry",
    keywords: ["oxidizer", "oxygen oxygen single bond"],
  },
  {
    id: "ammonia",
    name: "Ammonia",
    formula: "NH3",
    functionalGroups: ["amine", "base"],
    commonAliases: ["azane"],
    difficulty: "Introductory",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["ammonia"],
    formulaId: PH_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["trigonal pyramidal", "lone pair", "weak base"],
  },
  {
    id: "methane",
    name: "Methane",
    formula: "CH4",
    functionalGroups: ["alkane"],
    commonAliases: ["natural gas"],
    difficulty: "Introductory",
    reactionGraphLinks: ["combustion"],
    visualizerLinks: ["methane"],
    relatedReactions: [{ id: "rxn-combustion-methane", label: "Methane combustion" }],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkanes",
    keywords: ["tetrahedral", "saturated hydrocarbon"],
  },
  {
    id: "ethane",
    name: "Ethane",
    formula: "C2H6",
    functionalGroups: ["alkane"],
    commonAliases: [],
    difficulty: "Introductory",
    reactionGraphLinks: ["alkene pathway"],
    visualizerLinks: ["ethane"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkanes",
    keywords: ["single bond", "saturated"],
  },
  {
    id: "ethene",
    name: "Ethene",
    formula: "C2H4",
    functionalGroups: ["alkene"],
    commonAliases: ["ethylene"],
    difficulty: "Introductory",
    reactionGraphLinks: ["alkene pathway"],
    visualizerLinks: ["ethene"],
    relatedReactions: [
      { id: "rxn-organic-ethene-bromine", label: "Alkene bromination" },
      { id: "rxn-organic-ethene-hydrogen", label: "Alkene hydrogenation" },
    ],
    relatedMechanisms: [
      { id: "alkene-bromination", label: "Alkene bromination" },
      { id: "alkene-hydrogenation", label: "Alkene hydrogenation" },
      { id: "alkene-hydration", label: "Alkene hydration" },
    ],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkenes",
    keywords: ["double bond", "pi bond", "addition"],
  },
  {
    id: "ethyne",
    name: "Ethyne",
    formula: "C2H2",
    functionalGroups: ["alkyne"],
    commonAliases: ["acetylene"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alkyne reactions"],
    visualizerLinks: ["ethyne"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkynes",
    keywords: ["triple bond", "linear", "pi bonds"],
  },
  {
    id: "propane",
    name: "Propane",
    formula: "C3H8",
    functionalGroups: ["alkane"],
    commonAliases: [],
    difficulty: "Introductory",
    reactionGraphLinks: ["combustion"],
    visualizerLinks: ["propane"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkanes",
    keywords: ["saturated hydrocarbon"],
  },
  {
    id: "propene",
    name: "Propene",
    formula: "C3H6",
    functionalGroups: ["alkene"],
    commonAliases: ["propylene"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alkene hydration"],
    visualizerLinks: ["propene"],
    relatedReactions: [{ id: "rxn-organic-propene-hydration", label: "Propene hydration" }],
    relatedMechanisms: [{ id: "alkene-hydration", label: "Alkene hydration" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkenes",
    keywords: ["double bond", "addition", "markovnikov"],
  },
  {
    id: "butane",
    name: "Butane",
    formula: "C4H10",
    functionalGroups: ["alkane"],
    commonAliases: [],
    difficulty: "Introductory",
    reactionGraphLinks: ["combustion"],
    visualizerLinks: ["butane"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkanes",
    keywords: ["saturated hydrocarbon"],
  },
  {
    id: "methanol",
    name: "Methanol",
    formula: "CH3OH",
    functionalGroups: ["alcohol"],
    commonAliases: ["methyl alcohol"],
    difficulty: "Introductory",
    reactionGraphLinks: ["alcohol pathway"],
    visualizerLinks: ["methanol"],
    relatedMechanisms: [{ id: "alcohol-oxidation", label: "Alcohol oxidation" }],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "alcohols",
    keywords: ["oh", "hydroxyl", "primary alcohol"],
  },
  {
    id: "ethanol",
    name: "Ethanol",
    formula: "C2H5OH",
    functionalGroups: ["alcohol"],
    commonAliases: ["ethyl alcohol", "alcohol"],
    difficulty: "Introductory",
    reactionGraphLinks: ["alcohol pathway", "esterification"],
    visualizerLinks: ["ethanol"],
    relatedReactions: [
      { id: "rxn-organic-ethanol-oxidation", label: "Ethanol oxidation" },
      { id: "rxn-organic-ethanol-ethanoic-acid", label: "Esterification" },
    ],
    relatedMechanisms: [
      { id: "alcohol-oxidation", label: "Alcohol oxidation" },
      { id: "esterification", label: "Esterification" },
    ],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "alcohols",
    recommendedCurriculumTopics: [
      { id: "alcohols", label: "Alcohols" },
      { id: "organic-mechanisms", label: "Organic Mechanisms" },
    ],
    keywords: ["oh", "hydroxyl", "primary alcohol", "oxidation"],
  },
  {
    id: "propan-1-ol",
    name: "Propan-1-ol",
    formula: "C3H7OH",
    functionalGroups: ["alcohol"],
    commonAliases: ["1-propanol", "n-propanol", "propanol"],
    difficulty: "Introductory",
    reactionGraphLinks: ["alcohol pathway"],
    visualizerLinks: ["propan-1-ol"],
    relatedMechanisms: [{ id: "alcohol-oxidation", label: "Alcohol oxidation" }],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "alcohols",
    keywords: ["primary alcohol", "hydroxyl"],
  },
  {
    id: "propan-2-ol",
    name: "Propan-2-ol",
    formula: "C3H8O",
    functionalGroups: ["alcohol"],
    commonAliases: ["2-propanol", "isopropanol", "isopropyl alcohol"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alcohol pathway"],
    visualizerLinks: ["propan-2-ol"],
    relatedMechanisms: [{ id: "alcohol-oxidation", label: "Alcohol oxidation" }],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "alcohols",
    keywords: ["secondary alcohol", "hydroxyl", "ketone oxidation product"],
  },
  {
    id: "phenol",
    name: "Phenol",
    formula: "C6H5OH",
    functionalGroups: ["phenol", "arene", "alcohol"],
    commonAliases: ["hydroxybenzene"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["aromatic pathway"],
    visualizerLinks: ["phenol"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "aromatics",
    keywords: ["benzene ring", "hydroxyl", "weak acid"],
  },
  {
    id: "methanal",
    name: "Methanal",
    formula: "CH2O",
    functionalGroups: ["aldehyde", "carbonyl"],
    commonAliases: ["formaldehyde"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["carbonyl pathway"],
    visualizerLinks: ["methanal"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["c=o", "carbonyl", "aldehyde"],
  },
  {
    id: "ethanal",
    name: "Ethanal",
    formula: "C2H4O",
    functionalGroups: ["aldehyde", "carbonyl"],
    commonAliases: ["acetaldehyde"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alcohol pathway"],
    visualizerLinks: ["ethanal"],
    relatedReactions: [{ id: "rxn-organic-ethanal-oxidation", label: "Ethanal oxidation" }],
    relatedMechanisms: [{ id: "carboxylic-acid-formation", label: "Carboxylic acid formation" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["c=o", "carbonyl", "aldehyde", "oxidation"],
  },
  {
    id: "propanal",
    name: "Propanal",
    formula: "C3H6O",
    functionalGroups: ["aldehyde", "carbonyl"],
    commonAliases: ["propionaldehyde"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["carbonyl pathway"],
    visualizerLinks: ["propanal"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["aldehyde", "carbonyl"],
  },
  {
    id: "acetone",
    name: "Acetone",
    formula: "C3H6O",
    functionalGroups: ["ketone", "carbonyl"],
    commonAliases: ["propanone"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["carbonyl pathway"],
    visualizerLinks: ["acetone"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["ketone", "c=o", "carbonyl"],
  },
  {
    id: "butanone",
    name: "Butanone",
    formula: "C4H8O",
    functionalGroups: ["ketone", "carbonyl"],
    commonAliases: ["methyl ethyl ketone", "2-butanone"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["carbonyl pathway"],
    visualizerLinks: ["butanone"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["ketone", "carbonyl"],
  },
  {
    id: "methanoic-acid",
    name: "Methanoic acid",
    formula: "CH2O2",
    functionalGroups: ["carboxylic acid"],
    commonAliases: ["formic acid"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["methanoic-acid"],
    formulaId: PH_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "carboxylic-acids",
    keywords: ["cooh", "acid", "carbonyl"],
  },
  {
    id: "ethanoic-acid",
    name: "Ethanoic acid",
    formula: "C2H4O2",
    functionalGroups: ["carboxylic acid"],
    commonAliases: ["acetic acid"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alcohol pathway", "esterification"],
    visualizerLinks: ["ethanoic-acid"],
    relatedReactions: [{ id: "rxn-organic-ethanol-ethanoic-acid", label: "Esterification" }],
    relatedMechanisms: [{ id: "esterification", label: "Esterification" }],
    formulaId: PH_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "carboxylic-acids",
    recommendedCurriculumTopics: [
      { id: "carboxylic-acids", label: "Carboxylic Acids" },
      { id: "esters", label: "Esters" },
    ],
    keywords: ["cooh", "acid", "vinegar", "carbonyl"],
  },
  {
    id: "propanoic-acid",
    name: "Propanoic acid",
    formula: "C3H6O2",
    functionalGroups: ["carboxylic acid"],
    commonAliases: ["propionic acid"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["esterification"],
    visualizerLinks: ["propanoic-acid"],
    relatedMechanisms: [{ id: "esterification", label: "Esterification" }],
    formulaId: PH_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "carboxylic-acids",
    keywords: ["cooh", "acid"],
  },
  {
    id: "benzoic-acid",
    name: "Benzoic acid",
    formula: "C7H6O2",
    functionalGroups: ["carboxylic acid", "arene"],
    commonAliases: [],
    difficulty: "Advanced",
    reactionGraphLinks: ["aromatic pathway"],
    visualizerLinks: ["benzoic-acid"],
    formulaId: PH_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "carboxylic-acids",
    keywords: ["benzene ring", "cooh", "aromatic acid"],
  },
  {
    id: "methyl-ethanoate",
    name: "Methyl ethanoate",
    formula: "C3H6O2",
    functionalGroups: ["ester"],
    commonAliases: ["methyl acetate"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["esterification"],
    visualizerLinks: ["methyl-ethanoate"],
    relatedMechanisms: [{ id: "esterification", label: "Esterification" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "esters",
    keywords: ["coo", "ester", "carbonyl"],
  },
  {
    id: "ethyl-ethanoate",
    name: "Ethyl ethanoate",
    formula: "C4H8O2",
    functionalGroups: ["ester"],
    commonAliases: ["ethyl acetate"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alcohol pathway", "esterification"],
    visualizerLinks: ["ethyl-ethanoate"],
    relatedReactions: [{ id: "rxn-organic-ethanol-ethanoic-acid", label: "Esterification" }],
    relatedMechanisms: [{ id: "esterification", label: "Esterification" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "esters",
    keywords: ["coo", "ester", "fruity smell"],
  },
  {
    id: "aspirin",
    name: "Aspirin",
    formula: "C9H8O4",
    functionalGroups: ["ester", "carboxylic acid", "arene"],
    commonAliases: ["acetylsalicylic acid"],
    difficulty: "Advanced",
    reactionGraphLinks: ["esterification", "aromatic pathway"],
    visualizerLinks: ["aspirin"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "esters",
    keywords: ["medicine", "ester", "carboxylic acid", "benzene"],
  },
  {
    id: "benzene",
    name: "Benzene",
    formula: "C6H6",
    functionalGroups: ["arene"],
    commonAliases: ["aromatic ring"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["aromatic pathway"],
    visualizerLinks: ["benzene"],
    relatedReactions: [{ id: "rxn-organic-benzene-nitration", label: "Benzene nitration" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Spectroscopy",
    examTopic: "Spectroscopy",
    curriculumTopicId: "aromatics",
    keywords: ["aromatic", "ring", "delocalized"],
  },
  {
    id: "toluene",
    name: "Toluene",
    formula: "C7H8",
    functionalGroups: ["arene", "alkylbenzene"],
    commonAliases: ["methylbenzene"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["aromatic pathway"],
    visualizerLinks: ["toluene"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Spectroscopy",
    examTopic: "Spectroscopy",
    curriculumTopicId: "aromatics",
    keywords: ["benzene ring", "methyl"],
  },
  {
    id: "nitrobenzene",
    name: "Nitrobenzene",
    formula: "C6H5NO2",
    functionalGroups: ["arene", "nitro"],
    commonAliases: [],
    difficulty: "Advanced",
    reactionGraphLinks: ["aromatic pathway"],
    visualizerLinks: ["nitrobenzene"],
    relatedReactions: [{ id: "rxn-organic-benzene-nitration", label: "Benzene nitration" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "aromatics",
    keywords: ["nitro", "electrophilic substitution"],
  },
  {
    id: "aniline",
    name: "Aniline",
    formula: "C6H7N",
    functionalGroups: ["amine", "arene"],
    commonAliases: ["phenylamine"],
    difficulty: "Advanced",
    reactionGraphLinks: ["aromatic pathway"],
    visualizerLinks: ["aniline"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "aromatics",
    keywords: ["amine", "benzene ring", "aromatic"],
  },
  {
    id: "chloroethane",
    name: "Chloroethane",
    formula: "C2H5Cl",
    functionalGroups: ["haloalkane"],
    commonAliases: ["ethyl chloride"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["substitution"],
    visualizerLinks: ["chloroethane"],
    relatedMechanisms: [
      { id: "sn1-substitution", label: "SN1 substitution" },
      { id: "sn2-substitution", label: "SN2 substitution" },
    ],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Mechanisms",
    examTopic: "Organic Mechanisms",
    curriculumTopicId: "organic-mechanisms",
    keywords: ["halide", "leaving group", "substitution"],
  },
  {
    id: "bromoethane",
    name: "Bromoethane",
    formula: "C2H5Br",
    functionalGroups: ["haloalkane"],
    commonAliases: ["ethyl bromide"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["substitution"],
    visualizerLinks: ["bromoethane"],
    relatedReactions: [{ id: "rxn-organic-bromoethane-oh", label: "Bromoethane substitution" }],
    relatedMechanisms: [
      { id: "sn2-substitution", label: "SN2 substitution" },
      { id: "e2-elimination", label: "E2 elimination" },
    ],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Mechanisms",
    examTopic: "Organic Mechanisms",
    curriculumTopicId: "organic-mechanisms",
    keywords: ["halide", "leaving group", "bromide"],
  },
  {
    id: "1-bromopropane",
    name: "1-Bromopropane",
    formula: "C3H7Br",
    functionalGroups: ["haloalkane"],
    commonAliases: ["propyl bromide"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["substitution", "elimination"],
    visualizerLinks: ["1-bromopropane"],
    relatedMechanisms: [
      { id: "sn2-substitution", label: "SN2 substitution" },
      { id: "e2-elimination", label: "E2 elimination" },
    ],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Organic Mechanisms",
    examTopic: "Organic Mechanisms",
    curriculumTopicId: "organic-mechanisms",
    keywords: ["haloalkane", "primary halide"],
  },
  {
    id: "ethylamine",
    name: "Ethylamine",
    formula: "C2H7N",
    functionalGroups: ["amine"],
    commonAliases: ["ethanamine"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["ethylamine"],
    formulaId: PH_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["amine", "base", "nh2"],
  },
  {
    id: "acetamide",
    name: "Acetamide",
    formula: "C2H5NO",
    functionalGroups: ["amide", "carbonyl"],
    commonAliases: ["ethanamide"],
    difficulty: "Advanced",
    reactionGraphLinks: ["carbonyl pathway"],
    visualizerLinks: ["acetamide"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["amide", "carbonyl", "n-h"],
  },
  {
    id: "acetonitrile",
    name: "Acetonitrile",
    formula: "C2H3N",
    functionalGroups: ["nitrile"],
    commonAliases: ["methyl cyanide"],
    difficulty: "Advanced",
    reactionGraphLinks: ["spectroscopy"],
    visualizerLinks: ["acetonitrile"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "IR Spectroscopy",
    examTopic: "IR Spectroscopy",
    curriculumTopicId: "functional-groups",
    keywords: ["c triple n", "nitrile", "cyanide"],
  },
  {
    id: "glucose",
    name: "Glucose",
    formula: "C6H12O6",
    functionalGroups: ["alcohol", "aldehyde"],
    commonAliases: ["dextrose"],
    difficulty: "Advanced",
    reactionGraphLinks: ["biochemistry"],
    visualizerLinks: ["glucose"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["sugar", "carbohydrate", "polyhydroxy"],
  },
  {
    id: "fructose",
    name: "Fructose",
    formula: "C6H12O6",
    functionalGroups: ["alcohol", "ketone"],
    commonAliases: ["fruit sugar"],
    difficulty: "Advanced",
    reactionGraphLinks: ["biochemistry"],
    visualizerLinks: ["fructose"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["sugar", "carbohydrate", "ketose"],
  },
  {
    id: "sucrose",
    name: "Sucrose",
    formula: "C12H22O11",
    functionalGroups: ["alcohol", "ether"],
    commonAliases: ["table sugar"],
    difficulty: "Advanced",
    reactionGraphLinks: ["biochemistry"],
    visualizerLinks: ["sucrose"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["disaccharide", "sugar", "glycosidic"],
  },
  {
    id: "sodium-chloride",
    name: "Sodium chloride",
    formula: "NaCl",
    functionalGroups: ["ionic compound", "salt"],
    commonAliases: ["table salt", "salt"],
    difficulty: "Introductory",
    reactionGraphLinks: ["acid-base pathway", "precipitation"],
    visualizerLinks: ["sodium-chloride"],
    relatedReactions: [
      { id: "rxn-neutralization-hcl-naoh", label: "Neutralization" },
      { id: "rxn-precip-agcl", label: "Silver chloride precipitation" },
    ],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Stoichiometry",
    examTopic: "Stoichiometry",
    curriculumTopicId: "stoichiometry",
    keywords: ["ionic", "lattice", "salt"],
  },
  {
    id: "hydrochloric-acid",
    name: "Hydrochloric acid",
    formula: "HCl",
    functionalGroups: ["acid"],
    commonAliases: ["muriatic acid", "hydrogen chloride"],
    difficulty: "Introductory",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["hydrochloric-acid"],
    relatedReactions: [{ id: "rxn-neutralization-hcl-naoh", label: "Neutralization" }],
    formulaId: PH_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["strong acid", "chloride"],
  },
  {
    id: "sodium-hydroxide",
    name: "Sodium hydroxide",
    formula: "NaOH",
    functionalGroups: ["base", "ionic compound"],
    commonAliases: ["lye", "caustic soda"],
    difficulty: "Introductory",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["sodium-hydroxide"],
    relatedReactions: [{ id: "rxn-neutralization-hcl-naoh", label: "Neutralization" }],
    formulaId: PH_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["strong base", "hydroxide"],
  },
  {
    id: "carbon-dioxide",
    name: "Carbon dioxide",
    formula: "CO2",
    functionalGroups: ["oxide", "gas"],
    commonAliases: [],
    difficulty: "Introductory",
    reactionGraphLinks: ["combustion", "gas laws"],
    visualizerLinks: ["carbon-dioxide"],
    formulaId: "gases-ideal-gas-law",
    practiceTopic: "Chemistry Calculations",
    examTopic: "Chemistry Calculations",
    curriculumTopicId: "gas-laws",
    keywords: ["linear", "greenhouse gas", "combustion product"],
  },
  {
    id: "carbon-monoxide",
    name: "Carbon monoxide",
    formula: "CO",
    functionalGroups: ["oxide", "gas"],
    commonAliases: [],
    difficulty: "Intermediate",
    reactionGraphLinks: ["combustion"],
    visualizerLinks: ["carbon-monoxide"],
    formulaId: "gases-ideal-gas-law",
    practiceTopic: "Chemistry Calculations",
    examTopic: "Chemistry Calculations",
    curriculumTopicId: "gas-laws",
    keywords: ["toxic gas", "incomplete combustion"],
  },
  {
    id: "sulfuric-acid",
    name: "Sulfuric acid",
    formula: "H2SO4",
    functionalGroups: ["acid"],
    commonAliases: [],
    difficulty: "Intermediate",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["sulfuric-acid"],
    formulaId: PH_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["strong acid", "diprotic"],
  },
  {
    id: "nitric-acid",
    name: "Nitric acid",
    formula: "HNO3",
    functionalGroups: ["acid"],
    commonAliases: [],
    difficulty: "Intermediate",
    reactionGraphLinks: ["acid-base pathway", "aromatic nitration"],
    visualizerLinks: ["nitric-acid"],
    relatedReactions: [{ id: "rxn-organic-benzene-nitration", label: "Benzene nitration" }],
    formulaId: PH_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["strong acid", "nitration"],
  },
  {
    id: "calcium-carbonate",
    name: "Calcium carbonate",
    formula: "CaCO3",
    functionalGroups: ["carbonate", "ionic compound"],
    commonAliases: ["limestone", "chalk"],
    difficulty: "Introductory",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["calcium-carbonate"],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Stoichiometry",
    examTopic: "Stoichiometry",
    curriculumTopicId: "stoichiometry",
    keywords: ["carbonate", "precipitate"],
  },
  {
    id: "sodium-carbonate",
    name: "Sodium carbonate",
    formula: "Na2CO3",
    functionalGroups: ["carbonate", "ionic compound", "base"],
    commonAliases: ["washing soda"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["sodium-carbonate"],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["carbonate", "base"],
  },
  {
    id: "sodium-bicarbonate",
    name: "Sodium bicarbonate",
    formula: "NaHCO3",
    functionalGroups: ["carbonate", "ionic compound", "base"],
    commonAliases: ["sodium hydrogen carbonate", "baking soda"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["acid-base pathway"],
    visualizerLinks: ["sodium-bicarbonate"],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Acids and Bases",
    examTopic: "Acids and Bases",
    curriculumTopicId: "acids-and-bases",
    keywords: ["bicarbonate", "buffer", "base"],
  },
  {
    id: "copper-ii-sulfate",
    name: "Copper(II) sulfate",
    formula: "CuSO4",
    functionalGroups: ["ionic compound", "transition metal salt"],
    commonAliases: ["cupric sulfate", "copper sulfate"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["redox"],
    visualizerLinks: ["copper-ii-sulfate"],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Redox",
    examTopic: "Redox",
    curriculumTopicId: "electrochemistry",
    keywords: ["blue", "transition metal", "sulfate"],
  },
  {
    id: "silver-chloride",
    name: "Silver chloride",
    formula: "AgCl",
    functionalGroups: ["ionic compound", "precipitate"],
    commonAliases: [],
    difficulty: "Introductory",
    reactionGraphLinks: ["precipitation"],
    visualizerLinks: ["silver-chloride"],
    relatedReactions: [{ id: "rxn-precip-agcl", label: "Silver chloride precipitation" }],
    formulaId: STOICHIOMETRY_FORMULA,
    practiceTopic: "Precipitation",
    examTopic: "Precipitation",
    curriculumTopicId: "stoichiometry",
    keywords: ["white precipitate", "chloride test"],
  },
  {
    id: "potassium-permanganate",
    name: "Potassium permanganate",
    formula: "KMnO4",
    functionalGroups: ["oxidizing agent", "ionic compound"],
    commonAliases: ["permanganate"],
    difficulty: "Advanced",
    reactionGraphLinks: ["redox"],
    visualizerLinks: ["potassium-permanganate"],
    formulaId: "electrochemistry-ecell",
    practiceTopic: "Redox",
    examTopic: "Redox",
    curriculumTopicId: "electrochemistry",
    keywords: ["purple", "oxidation", "redox"],
  },
  {
    id: "potassium-dichromate",
    name: "Potassium dichromate",
    formula: "K2Cr2O7",
    functionalGroups: ["oxidizing agent", "ionic compound"],
    commonAliases: ["dichromate"],
    difficulty: "Advanced",
    reactionGraphLinks: ["redox", "alcohol oxidation"],
    visualizerLinks: ["potassium-dichromate"],
    relatedMechanisms: [{ id: "alcohol-oxidation", label: "Alcohol oxidation" }],
    formulaId: "electrochemistry-ecell",
    practiceTopic: "Redox",
    examTopic: "Redox",
    curriculumTopicId: "electrochemistry",
    keywords: ["orange", "oxidation", "alcohol test"],
  },
  {
    id: "cyclohexane",
    name: "Cyclohexane",
    formula: "C6H12",
    functionalGroups: ["cycloalkane"],
    commonAliases: [],
    difficulty: "Intermediate",
    reactionGraphLinks: ["organic reactions"],
    visualizerLinks: ["cyclohexane"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "alkanes",
    keywords: ["ring", "chair", "saturated"],
  },
  {
    id: "cyclohexene",
    name: "Cyclohexene",
    formula: "C6H10",
    functionalGroups: ["alkene", "cycloalkene"],
    commonAliases: [],
    difficulty: "Intermediate",
    reactionGraphLinks: ["alkene pathway"],
    visualizerLinks: ["cyclohexene"],
    relatedMechanisms: [{ id: "alkene-bromination", label: "Alkene bromination" }],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Organic Reactions",
    examTopic: "Organic Reactions",
    curriculumTopicId: "alkenes",
    keywords: ["ring", "double bond"],
  },
  {
    id: "diethyl-ether",
    name: "Diethyl ether",
    formula: "C4H10O",
    functionalGroups: ["ether"],
    commonAliases: ["ethyl ether"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["functional groups"],
    visualizerLinks: ["diethyl-ether"],
    formulaId: ORGANIC_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["c-o-c", "ether"],
  },
  {
    id: "acetic-anhydride",
    name: "Acetic anhydride",
    formula: "C4H6O3",
    functionalGroups: ["acid anhydride", "carbonyl"],
    commonAliases: ["ethanoic anhydride"],
    difficulty: "Advanced",
    reactionGraphLinks: ["esterification"],
    visualizerLinks: ["acetic-anhydride"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "carbonyl-chemistry",
    keywords: ["anhydride", "carbonyl", "acylation"],
  },
  {
    id: "glycine",
    name: "Glycine",
    formula: "C2H5NO2",
    functionalGroups: ["amine", "carboxylic acid", "amino acid"],
    commonAliases: ["aminoacetic acid"],
    difficulty: "Advanced",
    reactionGraphLinks: ["biochemistry"],
    visualizerLinks: ["glycine"],
    formulaId: PH_FORMULA,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["zwitterion", "amino acid", "amine", "acid"],
  },
  {
    id: "urea",
    name: "Urea",
    formula: "CH4N2O",
    functionalGroups: ["amide", "carbonyl"],
    commonAliases: ["carbamide"],
    difficulty: "Intermediate",
    reactionGraphLinks: ["functional groups"],
    visualizerLinks: ["urea"],
    formulaId: ORGANIC_UNSATURATION,
    practiceTopic: "Functional Group Identification",
    examTopic: "Functional Group Identification",
    curriculumTopicId: "functional-groups",
    keywords: ["amide", "carbonyl", "nitrogen"],
  },
]

export function getStructureScannerRecord(id: string): StructureScannerRecord | undefined {
  return STRUCTURE_SCANNER_RECORDS.find((record) => record.id === id)
}

export function getStructureScannerMetrics() {
  const functionalGroups = new Set<string>()
  const visualizerLinks = new Set<string>()
  const reactionGraphLinks = new Set<string>()

  for (const record of STRUCTURE_SCANNER_RECORDS) {
    record.functionalGroups.forEach((group) => functionalGroups.add(group))
    record.visualizerLinks.forEach((link) => visualizerLinks.add(link))
    record.reactionGraphLinks.forEach((link) => reactionGraphLinks.add(link))
  }

  return {
    compounds: STRUCTURE_SCANNER_RECORDS.length,
    functionalGroups: functionalGroups.size,
    visualizerLinks: visualizerLinks.size,
    reactionGraphLinks: reactionGraphLinks.size,
  }
}
